import { describe, it, expect } from 'vitest';
import { createCity, advance, applyTool, refreshCity, catchUp, TICK_MS } from '../shared/simulation/engine';
import { setTax, taxRate, togglePolicy, updateGovernance, analyzeGovernance, createDistrict, adoptNeighborhood, renameDistrict, setPriority, maintenanceBudget, rehouseDisplaced, objectiveProgress, governanceOverlayValue } from '../shared/simulation/governance';
import { GOVERNANCE, POLICIES } from '../shared/simulation/governance-config';
import { decodeCity } from '../shared/simulation/save-format';
import { updateInfrastructure } from '../shared/simulation/infrastructure';
import { attractiveness, updateLandValues } from '../shared/simulation/development';
import { operateBusinesses, updateDemand } from '../shared/simulation/economy';
import { updateLiving, householdSamples } from '../shared/simulation/living-city';
import { roadPerformance } from '../shared/simulation/road-network';
import { governancePanel } from '../client/ui/governance-panels';
import { chooseModes, modeCounts } from '../shared/simulation/mobility';
import type { TravelFlow, TransportRoute } from '../shared/types/mobility';

function ramp(c:ReturnType<typeof createCity>,days=40){for(let i=0;i<days;i++){c.tick++;updateGovernance(c);}}
describe('bounded, gradual municipal governance',()=>{
  it('starts with neutral taxes, no policy costs and no changes to existing capacity',()=>{const c=createCity(0);expect(c.version).toBe(9);expect(c.governance.policies).toEqual([]);expect(c.governance.programCost).toBe(0);expect(taxRate(c,'residential')).toBe(.25);expect(c.population).toBe(500);expect(c.governance.housing.units).toBe(Math.ceil(c.housingCapacity/4));});
  it('rejects excessive, negative and non-finite taxes',()=>{const c=createCity(0);for(const n of [-1,1,Infinity,NaN])expect(setTax(c,'residential',n)).not.toBe('');expect(c.governance.taxes.target.residential).toBe(.25);});
  it('phases taxes in and prevents repeated decision exploitation',()=>{const c=createCity(0);expect(setTax(c,'commercial',8)).toBe('');expect(taxRate(c,'commercial')).toBe(3.5);expect(setTax(c,'commercial',1)).toContain('review');ramp(c,1);expect(taxRate(c,'commercial')).toBeGreaterThan(3.5);expect(taxRate(c,'commercial')).toBeLessThan(4);ramp(c,39);expect(taxRate(c,'commercial')).toBeGreaterThan(7);});
  it('higher taxes raise revenue and lower profitability and demand gradually',()=>{const low=createCity(0),high=structuredClone(low);setTax(high,'commercial',8);ramp(high);refreshCity(low);refreshCity(high);expect(high.taxes.commercial).toBeGreaterThan(low.taxes.commercial);operateBusinesses(low);operateBusinesses(high);expect(high.tiles[462].building!.business!.netProfit).toBeLessThan(low.tiles[462].building!.business!.netProfit);updateDemand(low);updateDemand(high);expect(high.demand.commercial).toBeLessThan(low.demand.commercial);});
  it('policies delay benefits, cost money and wind down instead of toggling instantly',()=>{const c=createCity(0);togglePolicy(c,'affordable',null);ramp(c,6);expect(c.governance.policies[0].strength).toBe(0);ramp(c,22);expect(c.governance.policies[0].strength).toBeGreaterThan(.9);expect(c.governance.programCost).toBeGreaterThan(0);expect(togglePolicy(c,'affordable',null)).toContain('review');ramp(c,2);expect(togglePolicy(c,'affordable',null)).toBe('');expect(c.governance.policies[0].strength).toBeGreaterThan(0);ramp(c,21);expect(c.governance.policies[0].strength).toBe(0);expect(c.governance.programCost).toBe(0);});
  it('city and district copies of the same policy do not stack benefits or per-resident costs',()=>{const c=createCity(0);createDistrict(c,[332],'A');togglePolicy(c,'affordable',null);ramp(c);const before=c.governance.local[332].effects.rent,cost=c.governance.programCost;togglePolicy(c,'affordable',c.governance.districts[0].id);ramp(c);expect(c.governance.local[332].effects.rent).toBe(before);expect(c.governance.programCost-cost).toBeLessThanOrEqual(25000);});
  it('all supported policy definitions have explanatory benefits and requirements',()=>{expect(POLICIES.length).toBe(18);for(const p of POLICIES){expect(p.description.length).toBeGreaterThan(30);expect(p.requirements.length).toBeGreaterThan(10);expect(p.cost).toBeGreaterThan(0);}});
  it('district scopes affect only their governed land and leave neighborhood names intact',()=>{const c=createCity(0),names=c.clusters.map(x=>x.name);createDistrict(c,[332,333],'Unity');const d=c.governance.districts[0];togglePolicy(c,'affordable',d.id);ramp(c);expect(c.governance.local[332].effects.rent).toBe(-.2);expect(c.governance.local[334].effects.rent).toBe(0);expect(c.clusters.map(x=>x.name)).toEqual(names);renameDistrict(c,d.id,'Riverside');expect(d.name).toBe('Riverside');});
  it('adopts existing clusters without rewriting organic identity',()=>{const c=createCity(0),cluster=c.clusters[0];expect(adoptNeighborhood(c,cluster.id)).toBe('');expect(c.governance.districts[0].neighborhoodIds).toContain(cluster.id);expect(c.clusters[0].name).toBe(cluster.name);});
  it('district ownership is disjoint, ignores protected tiles, and rejects empty selection',()=>{const c=createCity(0);createDistrict(c,[332,333,332],'A');createDistrict(c,[332,334],'B');expect(c.governance.districts[1].tiles).toEqual([334]);expect(createDistrict(c,[-1,1024],'Bad')).toContain('Choose');expect(createDistrict(c,[332],'Overlap')).toContain('Choose');});
});
describe('housing, affordability, environmental and development interactions',()=>{
  it('job growth with fixed housing creates real housing pressure and an actionable challenge',()=>{const c=createCity(0);c.jobs=5000;analyzeGovernance(c);expect(c.governance.housing.pressure).toBe(100);const challenge=c.governance.challenges.find(x=>x.kind==='housing')!;expect(challenge.causes.length).toBeGreaterThan(0);expect(challenge.responses.length).toBeGreaterThan(1);expect(challenge.resolved).toBe(false);});
  it('affordable support lowers household rent without inventing housing capacity',()=>{const a=createCity(0);a.jobs=5000;analyzeGovernance(a,false);const b=structuredClone(a),capacity=b.housingCapacity;togglePolicy(b,'affordable',null);ramp(b,80);expect(b.governance.housing.averageRent).toBeLessThan(a.governance.housing.averageRent);expect(b.governance.housing.affordability).toBeGreaterThan(a.governance.housing.affordability);expect(b.housingCapacity).toBe(capacity);});
  it('rent is smoothed and bounded even at extreme demand',()=>{const c=createCity(0);const before=c.governance.local[332].rent;c.jobs=1000000;analyzeGovernance(c);expect(Math.abs(c.governance.local[332].rent-before)).toBeLessThan(15000);for(let i=0;i<100;i++)analyzeGovernance(c);for(const l of c.governance.local){expect(l.rent).toBeLessThanOrEqual(GOVERNANCE.rentMaximum);expect(l.rent).toBeGreaterThanOrEqual(GOVERNANCE.rentMinimum);}});
  it('cheaper local housing and better services improve migration attractiveness',()=>{const c=createCity(0);createDistrict(c,[332],'A');togglePolicy(c,'affordable',c.governance.districts[0].id);ramp(c,80);expect(c.governance.local[332].migration).toBeGreaterThanOrEqual(c.governance.local[334].migration);});
  it('district housing and job statistics reflect the actual buildings',()=>{const c=createCity(0);createDistrict(c,[332,462],'Mixed');analyzeGovernance(c);const d=c.governance.districts[0];expect(d.metrics.population).toBe(100);expect(d.metrics.jobs).toBe(c.tiles[462].building!.maximumJobs);expect(d.metrics.households).toBe(25);expect(d.metrics.businesses).toBe(1);});
  it('policies contribute explanations to private development without bypassing road access',()=>{const c=createCity(0);applyTool(c,10,10,'residential');togglePolicy(c,'density',null);ramp(c);const a=attractiveness(c,c.tiles[330]);expect(a.factors.some(f=>f.label==='Governance policy support'&&f.value>0)).toBe(true);expect(a.eligible).toBe(false);});
  it('environment responds to local traffic, waste and public green space',()=>{const c=createCity(0);analyzeGovernance(c,false);const before=c.governance.local[332].environment;c.tiles[332].mobility.congestion=100;c.tiles[332].publicServices.uncollectedWaste=30;analyzeGovernance(c,false);expect(c.governance.local[332].environment).toBeLessThan(before);});
  it('environment differences affect land value without unlimited bonuses',()=>{const a=createCity(0),b=structuredClone(a);a.governance.local.forEach(l=>l.environment=100);b.governance.local.forEach(l=>l.environment=0);updateLandValues(a);updateLandValues(b);expect(a.tiles[332].landValue).toBeGreaterThan(b.tiles[332].landValue);expect(a.tiles.every(t=>t.landValue<=100)).toBe(true);});
  it('informal clearance retains residents, costs money and creates a recovery path',()=>{const c=createCity(0);c.tiles[332].building!.tenure='informal';const before=c.population;applyTool(c,12,10,'bulldoze');expect(c.population).toBe(before);expect(c.occupiedHousing).toBe(before-100);expect(c.governance.housing.displacedResidents).toBe(100);expect(c.governance.clearanceShock).toBeGreaterThan(0);rehouseDisplaced(c);refreshCity(c);expect(c.governance.housing.rehoused).toBeGreaterThan(0);expect(c.population).toBe(before);});
  it('residents leave gradually only after prolonged failure to rehouse',()=>{const c=createCity(0);for(const t of c.tiles)if(t.building?.type==='residential')t.building.occupants=t.building.maximumOccupancy;refreshCity(c);c.governance.housing.displacedResidents=50;c.governance.housing.displacedSince=0;rehouseDisplaced(c);expect(c.governance.housing.displacedResidents).toBe(50);c.tick=91;rehouseDisplaced(c);expect(c.governance.housing.departed).toBe(1);expect(c.governance.housing.displacedResidents).toBe(49);});
  it('community integration is quicker with funded support but still needs actual utilities',()=>{const a=createCity(0),b=structuredClone(a);for(const c of [a,b]){c.tiles[332].building!.tenure='informal';c.tiles[332].services.powerReliability=90;c.tiles[332].services.waterReliability=90;c.tiles[332].services.drainageQuality=90;c.tiles[332].services.floodDepth=0;}togglePolicy(b,'integration',null);ramp(b);updateLiving(a);updateLiving(b);expect(b.tiles[332].building!.integrationProgress).toBeGreaterThan(a.tiles[332].building!.integrationProgress);});
  it('household concerns reveal an actual housing-cost problem',()=>{const c=createCity(0);for(const l of c.governance.local)l.affordability=0;expect(householdSamples(c).some(h=>h.concern.includes('Housing costs'))).toBe(true);});
});
describe('municipal spending, challenges and persistence',()=>{
  it('maintenance priority costs more and improves existing asset condition gradually',()=>{const a=createCity(0),b=structuredClone(a);setPriority(a,'power','low');setPriority(b,'power','high');for(let i=0;i<60;i++){a.tick++;b.tick++;updateInfrastructure(a,true);updateInfrastructure(b,true);}expect(b.infrastructure.costs.power).toBeGreaterThan(a.infrastructure.costs.power);expect(b.tiles.filter(t=>t.infrastructure?.kind==='diesel')[0].infrastructure!.condition).toBeGreaterThan(a.tiles.filter(t=>t.infrastructure?.kind==='diesel')[0].infrastructure!.condition);expect(maintenanceBudget(b,'power')).toBe(120);});
  it('pedestrian policy trades local road capacity for walking opportunity',()=>{const a=createCity(0),b=structuredClone(a);togglePolicy(b,'pedestrian',null);ramp(b);expect(roadPerformance(b,b.tiles[333]).capacity).toBeLessThan(roadPerformance(a,a.tiles[333]).capacity);expect(b.governance.local[332].effects.walking).toBeGreaterThan(0);});
  it('pedestrian policy changes actual mode choice while conserving trips',()=>{const a=createCity(0),b=structuredClone(a);togglePolicy(b,'pedestrian',null);ramp(b);const flow:TravelFlow={id:'short',origin:332,destination:462,originName:'Homes',destinationName:'Shops',purpose:'shopping',trips:500,distance:.6,minutes:8,path:[333,397,461],modes:modeCounts()};const before=chooseModes(a,flow,45),after=chooseModes(b,flow,45);expect(after.walk).toBeGreaterThan(before.walk);expect(Object.values(after).reduce((a,b)=>a+b,0)).toBe(500);});
  it('transit priority favors real existing routes rather than inventing buses',()=>{const a=createCity(0);const route:TransportRoute={id:'bus-test',mode:'bus',origin:333,destination:461,originName:'Homes',destinationName:'Shops',waypoints:[333,461],path:[333,365,397,429,461],demand:500,ridership:0,vehicles:4,capacity:2000,averageSpeed:20,minutes:6,profitability:60,netProfit:10000,reliability:90,congestionImpact:0,age:30,poorDays:0,formalized:true,suspended:false,createdAt:0};a.mobility.routes=[route];const b=structuredClone(a);togglePolicy(b,'transit',null);ramp(b);const flow:TravelFlow={id:'commute',origin:332,destination:462,originName:'Homes',destinationName:'Shops',purpose:'work',trips:500,distance:.6,minutes:8,path:route.path,modes:modeCounts()};expect(chooseModes(b,flow,45).bus).toBeGreaterThan(chooseModes(a,flow,45).bus);expect(b.mobility.routes).toHaveLength(1);});
  it('persistent deficits create challenges and expenditure reduction resolves them',()=>{const c=createCity(0);c.income=100;c.expenses=10000;for(let i=0;i<13;i++){c.tick+=5;analyzeGovernance(c);}expect(c.governance.challenges.some(x=>x.kind==='budget'&&!x.resolved)).toBe(true);c.income=20000;for(let i=0;i<15;i++){c.tick+=5;analyzeGovernance(c);}expect(c.governance.challenges.some(x=>x.kind==='budget'&&!x.resolved)).toBe(false);});
  it('challenge resolution uses hysteresis and does not spam active history',()=>{const c=createCity(0);c.jobs=5000;analyzeGovernance(c);const count=c.history.length;for(let i=0;i<10;i++)analyzeGovernance(c);expect(c.history.length).toBe(count);c.jobs=100;c.growth=0;analyzeGovernance(c);expect(c.governance.challenges.find(x=>x.kind==='housing')?.resolved).toBe(true);});
  it('flood challenges focus an actually affected tile and preserve recurrence data',()=>{const c=createCity(0);c.tiles[332].services.floodDepth=60;c.tiles[332].services.floodEvents=3;analyzeGovernance(c);expect(c.governance.challenges.find(x=>x.kind==='flood')?.tileId).toBe(332);expect(c.governance.local[332].floodEvents).toBe(3);});
  it('objectives and forecasts query outcomes, not quests or arbitrary rewards',()=>{const c=createCity(0);expect(objectiveProgress(c,'affordable')).toBeGreaterThanOrEqual(0);expect(objectiveProgress(c,'resilient')).toBeLessThanOrEqual(100);expect(c.governance.forecast.annualBalance).toBe((c.income-c.expenses)*12);expect(governanceOverlayValue(c,c.tiles[332],'affordability')).toBe(c.governance.local[332].affordability);expect(governanceOverlayValue(c,c.tiles[332],'none')).toBeUndefined();});
  it('v6 migration preserves every pre-existing field and uses neutral governance',()=>{const old:any=JSON.parse(JSON.stringify(createCity(0)));delete old.governance;delete old.safety;delete old.transit;delete old.publicServices.funding.police;delete old.publicServices.costs.police;delete old.publicServices.stats.police;for(const t of old.tiles)delete t.publicServices.police;old.version=6;const before=structuredClone(old),migrated=decodeCity(old);const restored:any=structuredClone(migrated);delete restored.governance;delete restored.safety;delete restored.transit;delete restored.publicServices.funding.police;delete restored.publicServices.costs.police;delete restored.publicServices.stats.police;for(const t of restored.tiles)delete t.publicServices.police;restored.version=6;expect(restored).toEqual(before);expect(migrated.version).toBe(9);expect(migrated.governance.policies).toHaveLength(0);});
  it('rejects corrupt tax rates, duplicate boundaries and invalid policy references',()=>{const c=createCity(0);createDistrict(c,[332],'A');for(const mutate of [(v:any)=>v.governance.taxes.target.commercial=100,(v:any)=>v.governance.districts[0].tiles.push(332),(v:any)=>v.governance.policies.push({id:'bad',districtId:null,enabled:true,activationDate:0,changedAt:0,strength:1}),(v:any)=>v.governance.local[332].rent=NaN]){const bad=structuredClone(c);mutate(bad);expect(()=>decodeCity(bad)).toThrow();}});
  it('save round trip preserves pending policy activation, district boundaries and displaced residents',()=>{const c=createCity(0);createDistrict(c,[332],'A');togglePolicy(c,'affordable',c.governance.districts[0].id);applyTool(c,12,10,'bulldoze');expect(decodeCity(JSON.parse(JSON.stringify(c)))).toEqual(c);});
  it('offline replay is identical with taxes, district policies and displacement',()=>{const c=createCity(0);createDistrict(c,[332,334],'A');togglePolicy(c,'affordable',c.governance.districts[0].id);setTax(c,'commercial',6);applyTool(c,12,10,'bulldoze');const online=structuredClone(c),offline=decodeCity(JSON.parse(JSON.stringify(c)));advance(online,90);online.lastSimulatedTimestamp=90*TICK_MS;const report=catchUp(offline,90*TICK_MS);expect(offline).toEqual(online);expect(report.rentAfter).toBe(offline.governance.housing.averageRent);},30000);
  it('renders all governance views without adding permanent UI or interpreting names as HTML',()=>{const c=createCity(0);createDistrict(c,[332],'<script>bad</script>');for(const tab of ['Overview','Budget','Taxes','Policies','Districts','Housing','Development']){const html=governancePanel(c,tab,c.governance.districts[0].id);expect(html).toContain('data-governance-tab');expect(html).not.toContain('<script>bad');}});
  it('twenty simulated years keep capacities, prices, history and deterministic saves bounded',()=>{
    const c=createCity(0,731);createDistrict(c,[332,334,396,398,460,462],'Founding district');setTax(c,'commercial',4);setPriority(c,'drainage','high');
    const samples:number[]=[];
    for(let year=0;year<20;year++){advance(c,360);const h=c.governance.housing;expect(c.population).toBe(c.occupiedHousing+h.displacedResidents);expect(c.occupiedHousing).toBeLessThanOrEqual(c.housingCapacity);expect(c.employed).toBeLessThanOrEqual(c.workforce);expect(h.averageRent).toBeLessThanOrEqual(GOVERNANCE.rentMaximum);expect(h.averageRent).toBeGreaterThanOrEqual(GOVERNANCE.rentMinimum);expect(Number.isFinite(c.treasury)).toBe(true);expect(c.governance.policies).toHaveLength(0);expect(c.governance.challenges.length).toBeLessThanOrEqual(GOVERNANCE.challengeLimit);expect(c.history.length).toBeLessThanOrEqual(60);samples.push(c.population);}
    expect(c.governance.history).toHaveLength(240);expect(c.governance.housing.averageRent).toBeGreaterThan(0);expect(samples.every(n=>n>=0)).toBe(true);expect(c.treasury).toBeGreaterThan(0);expect(decodeCity(JSON.parse(JSON.stringify(c)))).toEqual(c);
    if(process.env.GOVERNANCE_REPORT)console.info('20-year governance balance',JSON.stringify({population:c.population,housing:c.housingCapacity,rent:c.governance.housing.averageRent,affordability:c.governance.housing.affordability,treasury:c.treasury,informalProperties:c.tiles.filter(t=>t.building?.tenure==='informal').length,history:c.governance.history.length}));
  },180000);
});
