import { describe, it, expect } from 'vitest';
import { createCity, applyTool, previewTool, advance, catchUp, TICK_MS, refreshCity } from '../shared/simulation/engine';
import { makeFacility, updatePublicServices, triggerFire, localServiceEffect } from '../shared/simulation/public-services';
import { serviceTravelMap, serviceCacheDiagnostics } from '../shared/simulation/public-service-access';
import { PUBLIC_SERVICES, emptyPublicTile, fundingEffect } from '../shared/simulation/public-service-config';
import { decodeCity } from '../shared/simulation/save-format';
import { updateMobility } from '../shared/simulation/mobility';
import { labourAndMigration, propertyValue, operateBusinesses } from '../shared/simulation/economy';
import { updateInfrastructure } from '../shared/simulation/infrastructure';
import { invalidateRoadGraph } from '../shared/simulation/road-network';
import { attractiveness, updateLandValues } from '../shared/simulation/development';
import { cityActivity } from '../shared/simulation/activity';
import type { FacilityKind } from '../shared/types/public-services';
import { publicServiceFixture } from '../shared/simulation/public-service-fixtures';
import { updateClusters } from '../shared/simulation/development';
import { setWeather } from '../shared/simulation/weather';
import { offlineHtml } from '../client/ui/panels';

function fixture() {
  const city=createCity(0,731);
  for(const t of city.tiles){t.terrain='land';t.services.floodDepth=0;t.services.floodRisk=0;t.services.powerReliability=100;t.services.waterReliability=100;}
  return city;
}
function facility(city:ReturnType<typeof fixture>,kind:FacilityKind,x=12,y=8){
  const f=makeFacility(city,y*32+x,kind);
  for(const id of f.tiles){const t=city.tiles[id];t.road=false;t.roadClass=null;t.zone=null;t.building=null;t.infrastructure=null;t.publicFacility=f.id;}
  f.employeesAvailable=f.employeesRequired;city.publicServices.facilities.push(f);city.publicServices.revision++;updatePublicServices(city,false);return f;
}
describe('road-aware public facilities',()=>{
  it('derives primary and secondary school demand from occupied homes',()=>{const c=fixture();updatePublicServices(c,false);expect(c.publicServices.stats.education.demand).toBe(100);});
  it('provides finite staffed seats and distinguishes reach from capacity',()=>{const c=fixture(),f=facility(c,'primary-school');expect(f.served).toBeGreaterThan(0);expect(f.served).toBeLessThanOrEqual(f.effectiveCapacity);expect(c.tiles[332].publicServices.education.access).toBeGreaterThan(c.tiles[332].publicServices.education.served);});
  it('reports overcrowding when a connected school cannot meet demand',()=>{const c=fixture(),f=facility(c,'primary-school');for(const t of c.tiles)if(t.building?.type==='residential'){t.building.occupants=20000;t.building.maximumOccupancy=20000;}updatePublicServices(c,false);expect(f.status).toBe('overcrowded');expect(f.currentUsage).toBeGreaterThan(f.effectiveCapacity);expect(c.publicServices.stats.education.served).toBeLessThan(c.publicServices.stats.education.demand);});
  it('does not transfer unused secondary seats into primary capacity',()=>{const c=fixture();facility(c,'secondary-school',14,7);expect(c.tiles[332].publicServices.primary).toBe(0);expect(c.publicServices.stats.education.served).toBeLessThanOrEqual(c.population*.08);});
  it('does not grant access across disconnected roads',()=>{const c=fixture(),f=facility(c,'phc',20,8);c.tiles[8*32+21].road=true;invalidateRoadGraph(c);c.publicServices.revision++;updatePublicServices(c,false);expect(f.served).toBe(0);expect(c.tiles[332].publicServices.healthcare.access).toBe(0);});
  it('reduces accessible service as congestion increases travel time',()=>{const c=fixture(),f=facility(c,'fire-station',12,0),id=14*32+12;const before=serviceTravelMap(c,f)[id];for(const t of c.tiles)if(t.road)t.mobility.congestion=95;invalidateRoadGraph(c);expect(serviceTravelMap(c,f)[id]).toBeGreaterThan(before);});
  it('caches service access until road or footprint state changes',()=>{const c=fixture(),f=facility(c,'phc');const a=serviceTravelMap(c,f),count=serviceCacheDiagnostics(c).rebuilds;expect(serviceTravelMap(c,f)).toBe(a);expect(serviceCacheDiagnostics(c).rebuilds).toBe(count);c.publicServices.revision++;expect(serviceTravelMap(c,f)).not.toBe(a);});
  it('reserves the full hospital footprint and rejects overlap',()=>{const c=fixture();expect(applyTool(c,18,6,'hospital')).toBe('');const f=c.publicServices.facilities[0];expect(f.tiles).toHaveLength(4);expect(f.tiles.every(id=>c.tiles[id].publicFacility===f.id)).toBe(true);expect(previewTool(c,19,7,'road').status).toBe('invalid');expect(applyTool(c,19,7,'bulldoze')).toBe('');expect(c.publicServices.facilities).toHaveLength(0);expect(f.tiles.every(id=>c.tiles[id].publicFacility===null)).toBe(true);});
  it('rejects footprints crossing the map boundary or protected terrain',()=>{const c=fixture();expect(previewTool(c,31,31,'hospital').status).toBe('invalid');c.tiles[7*32+19].terrain='water';expect(previewTool(c,18,6,'hospital').status).toBe('invalid');});
});
describe('capacity, workforce, utilities and funding',()=>{
  it('hospital capacity and costs exceed a primary health centre',()=>{expect(PUBLIC_SERVICES.hospital.capacity).toBeGreaterThan(PUBLIC_SERVICES.phc.capacity);expect(PUBLIC_SERVICES.hospital.monthlyCost).toBeGreaterThan(PUBLIC_SERVICES.phc.monthlyCost);});
  it('power and water failures lower healthcare quality and capacity',()=>{const c=fixture(),f=facility(c,'phc'),quality=f.serviceQuality,capacity=f.effectiveCapacity;c.tiles[f.location].services.powerReliability=0;c.tiles[f.location].services.waterReliability=0;updatePublicServices(c,false);expect(f.serviceQuality).toBeLessThan(quality*.5);expect(f.effectiveCapacity).toBeLessThan(capacity*.5);expect(f.status).toBe('utility-disrupted');});
  it('adds facility electricity/water demand to the utility network',()=>{const c=fixture();updateInfrastructure(c,false);const power=c.infrastructure.power.demand,water=c.infrastructure.water.demand;const f=facility(c,'phc');updateInfrastructure(c,false);expect(c.infrastructure.power.demand-power).toBeCloseTo(f.powerRequired);expect(c.infrastructure.water.demand-water).toBeCloseTo(f.waterRequired);});
  it('understaffing reduces actual capacity',()=>{const c=fixture(),f=facility(c,'primary-school');const capacity=f.effectiveCapacity;f.employeesAvailable=7;updatePublicServices(c,false);expect(f.effectiveCapacity).toBeCloseTo(capacity*.25);expect(f.status).toBe('understaffed');});
  it('suspending a facility removes its occupied public jobs and service',()=>{const c=fixture(),f=facility(c,'phc');expect(c.publicServices.employed).toBe(24);f.active=false;updatePublicServices(c,false);refreshCity(c);expect(f.employeesAvailable).toBe(0);expect(c.publicServices.employed).toBe(0);expect(f.effectiveCapacity).toBe(0);expect(f.status).toBe('inactive');});
  it('public staff compete for reachable workers without creating people',()=>{const c=fixture();facility(c,'primary-school');facility(c,'phc',14,8);for(const f of c.publicServices.facilities)f.employeesAvailable=0;updateMobility(c,false,true);refreshCity(c);for(let i=0;i<15;i++){labourAndMigration(c);refreshCity(c);}expect(c.publicServices.employed).toBeGreaterThan(0);const actual=c.tiles.reduce((s,t)=>s+(t.building?.jobs??0),0)+c.publicServices.employed+c.living.informal.employed;expect(c.employed).toBe(actual);expect(actual).toBeLessThanOrEqual(c.workforce);expect(Object.keys(c.publicServices.jobTargets)).toHaveLength(2);});
  it('funding changes capacity/cost and overfunding has diminishing returns',()=>{const c=fixture(),f=facility(c,'phc'),normal=f.effectiveCapacity,cost=f.monthlyOperatingCost;c.publicServices.funding.healthcare=50;updatePublicServices(c,false);expect(f.effectiveCapacity).toBeCloseTo(normal*.5);expect(f.monthlyOperatingCost).toBeLessThan(cost);c.publicServices.funding.healthcare=150;updatePublicServices(c,false);expect(f.effectiveCapacity).toBeCloseTo(normal*1.15);expect(fundingEffect(150)).toBe(1.15);});
  it('treasury deficits cause funding strain instead of free service',()=>{const c=fixture(),f=facility(c,'phc'),capacity=f.effectiveCapacity;c.treasury=-100000000;updatePublicServices(c,false);expect(f.effectiveCapacity).toBeLessThan(capacity);expect(f.fundingLevel).toBeLessThan(100);});
  it('facility operating costs enter the automatic monthly budget',()=>{const c=fixture();refreshCity(c);const before=c.expenses;const f=facility(c,'phc');refreshCity(c);expect(c.expenses-before).toBeCloseTo(f.monthlyOperatingCost);});
  it('maintenance deterioration remains gradual and reacts to funding',()=>{const c=fixture(),f=facility(c,'phc');c.publicServices.funding.healthcare=50;updatePublicServices(c,true);expect(f.maintenanceCondition).toBeLessThan(100);expect(f.maintenanceCondition).toBeGreaterThan(99);});
});
describe('waste, parks, fire and neighborhood conditions',()=>{
  it('occupied homes and employers generate aggregate waste',()=>{const c=fixture();updatePublicServices(c,true);expect(c.publicServices.waste.generated).toBeGreaterThan(.3);expect(c.publicServices.waste.backlog).toBeCloseTo(c.publicServices.waste.generated);});
  it('a depot needs a reachable landfill before waste can disappear',()=>{const c=fixture();facility(c,'waste-depot');updatePublicServices(c,true);expect(c.publicServices.waste.collected).toBe(0);expect(c.publicServices.waste.backlog).toBeGreaterThan(0);facility(c,'landfill',14,17);updatePublicServices(c,true);expect(c.publicServices.waste.collected).toBeGreaterThan(0);expect(c.publicServices.waste.disposed).toBeGreaterThan(0);});
  it('overlapping depots conserve actual collection and disposal',()=>{const c=fixture();facility(c,'waste-depot');facility(c,'waste-depot',14,8);facility(c,'landfill',14,17);const before=c.publicServices.waste.backlog;updatePublicServices(c,true);expect(c.publicServices.waste.backlog).toBeCloseTo(Math.max(0,before+c.publicServices.waste.generated-c.publicServices.waste.collected));expect(c.publicServices.facilities.filter(f=>f.subtype==='landfill').reduce((s,f)=>s+f.storedWaste,0)).toBeCloseTo(c.publicServices.waste.disposed);});
  it('a full landfill cannot accept collection that would exceed storage',()=>{const c=fixture();facility(c,'waste-depot');const f=facility(c,'landfill',14,17);f.storedWaste=PUBLIC_SERVICES.landfill.wasteStorage!;updatePublicServices(c,true);expect(f.effectiveCapacity).toBe(0);expect(c.publicServices.waste.collected).toBe(0);expect(f.status).toBe('strained');});
  it('waste and landfill penalties are localized and bounded',()=>{const c=fixture(),near=c.tiles[332],far=c.tiles[0];near.publicServices.uncollectedWaste=100;near.publicServices.wasteGenerated=.05;expect(localServiceEffect(near).penalty).toBeGreaterThan(localServiceEffect(far).penalty);expect(localServiceEffect(near).penalty).toBeLessThanOrEqual(13);facility(c,'landfill',12,17);expect(c.tiles[17*32+12].publicServices.landfillPenalty).toBeGreaterThan(c.tiles[0].publicServices.landfillPenalty);});
  it('park access diminishes with travel distance and excludes protected water',()=>{const c=fixture(),f=facility(c,'pocket-park',4,4);c.tiles[5*32+4].terrain='water';c.tiles[4*32+5].terrain='water';c.publicServices.revision++;const map=serviceTravelMap(c,f);expect(map[f.location]).toBe(0);expect(map[4*32+3]).toBeGreaterThan(0);expect(map[0]).toBe(Infinity);});
  it('rain suppresses recreation activity and blocked footpaths invalidate access',()=>{const c=fixture(),f=facility(c,'pocket-park',11,10),activity=cityActivity(c,13).tiles[f.location].pedestrian;setWeather(c,'extreme-rain',8);expect(cityActivity(c,13).tiles[f.location].pedestrian).toBeLessThan(activity);const a=serviceTravelMap(c,f);c.tick++;c.tiles[10*32+10].services.floodDepth=90;expect(serviceTravelMap(c,f)).not.toBe(a);});
  it('keeps neighborhood Quality of Life when clusters are rebuilt',()=>{const c=fixture();updateClusters(c);updatePublicServices(c,true);updateClusters(c);expect(c.clusters.every(n=>Number.isFinite(n.qualityOfLife))).toBe(true);});
  it('newly built fire stations can dispatch to an ongoing incident',()=>{const c=fixture();triggerFire(c,332);expect(c.publicServices.fires[0].stationId).toBeNull();const f=facility(c,'fire-station');updatePublicServices(c,true);expect(c.publicServices.fires[0].stationId).toBe(f.id);});
  it('fire stations without staff cannot dispatch a response',()=>{
    const c=fixture(),f=facility(c,'fire-station');f.employeesAvailable=0;updatePublicServices(c,false);
    triggerFire(c,332);expect(c.publicServices.fires[0].stationId).toBeNull();expect(c.publicServices.fires[0].path).toHaveLength(0);
    f.employeesAvailable=f.employeesRequired;updatePublicServices(c,true);expect(c.publicServices.fires[0].stationId).toBe(f.id);
  });
  it('staffed parks improve nearby structural QoL gradually',()=>{const c=fixture();facility(c,'pocket-park',11,10);const near=c.tiles[332],far=c.tiles[0],before=near.publicServices.qualityOfLife;for(let i=0;i<30;i++)updatePublicServices(c,true);expect(near.publicServices.parks.quality).toBeGreaterThan(0);expect(near.publicServices.qualityOfLife).toBeGreaterThan(far.publicServices.qualityOfLife);expect(Math.abs(before-near.publicServices.qualityOfLife)).toBeLessThan(35);expect(c.publicServices.breakdown).toHaveProperty('Education');});
  it('service quality contributes to attractiveness and bounded land value',()=>{const c=fixture(),t=c.tiles[332];const before=attractiveness(c,t).score;facility(c,'primary-school');facility(c,'phc',14,8);updatePublicServices(c,false);expect(attractiveness(c,t).score).toBeGreaterThanOrEqual(before);const poor=structuredClone(c);poor.tiles.forEach(t=>t.publicServices=emptyPublicTile());updateLandValues(c);updateLandValues(poor);expect(c.tiles[332].landValue).toBeGreaterThan(poor.tiles[332].landValue);});
  it('a fire creates a real incident and the nearest reachable station responds',()=>{const c=fixture(),f=facility(c,'fire-station');expect(triggerFire(c,332)).toBe(true);expect(c.publicServices.fires[0].stationId).toBe(f.id);expect(c.publicServices.fires[0].path.length).toBeGreaterThan(0);expect(triggerFire(c,332)).toBe(false);updatePublicServices(c,false);expect(c.tiles[332].publicServices.fireActive).toBe(true);});
  it('good response reduces damage and subsequent repairs recover value',()=>{const served=fixture();facility(served,'fire-station');const poor=fixture();triggerFire(served,332);triggerFire(poor,332);for(let i=0;i<5;i++){served.tick++;poor.tick++;updatePublicServices(served,true);updatePublicServices(poor,true);}expect(served.tiles[332].publicServices.fireDamage).toBeLessThan(poor.tiles[332].publicServices.fireDamage);const damaged=poor.tiles[332],value=propertyValue(damaged),damage=damaged.publicServices.fireDamage;for(let i=0;i<20;i++){poor.tick++;updatePublicServices(poor,true);}expect(damaged.publicServices.fireDamage).toBeLessThan(damage);expect(propertyValue(damaged)).toBeGreaterThan(value);});
  it('fire damage reduces business output without deleting buildings',()=>{const c=fixture(),t=c.tiles[462];operateBusinesses(c);const before=t.building!.monthlyEconomicOutput;t.publicServices.fireDamage=60;operateBusinesses(c);expect(t.building!.monthlyEconomicOutput).toBeLessThan(before);expect(t.building).not.toBeNull();});
  it('generates service journeys and daytime school activity from actual facilities',()=>{const c=fixture();const f=facility(c,'primary-school');updateMobility(c,false,true);expect(c.mobility.flows.some(flow=>flow.purpose==='services')).toBe(true);expect(cityActivity(c,8).tiles[f.location].pedestrian).toBeGreaterThan(cityActivity(c,2).tiles[f.location].pedestrian);});
});
describe('safe persistence and deterministic offline services',()=>{
  it('shows meaningful offline service outcomes without repeating unchanged metrics',()=>{
    const c=fixture();facility(c,'fire-station');triggerFire(c,332);
    const report=catchUp(c,20*TICK_MS),html=offlineHtml(report);
    expect(html).toContain('Waste backlog');expect(html).toContain('Quality of Life');expect(html).toContain('Fire incidents contained');
    const unchanged=offlineHtml(catchUp(c,20*TICK_MS));
    expect(unchanged).not.toContain('Waste backlog');expect(unchanged).not.toContain('Quality of Life');expect(unchanged).not.toContain('Fire incidents contained');
  });
  it('builds all four service stress cities with actual occupied housing and valid saves',()=>{
    for(const n of [1000,10000,100000,500000] as const){const c=publicServiceFixture(n);expect(c.population).toBe(n);expect(c.tiles.reduce((sum,t)=>sum+(t.building?.occupants??0),0)).toBe(n);expect(()=>decodeCity(JSON.parse(JSON.stringify(c)))).not.toThrow();}
  },30000);
  it('round trips all service state including active incidents and local waste',()=>{const c=fixture();facility(c,'fire-station');facility(c,'phc',14,8);triggerFire(c,332);updatePublicServices(c,true);expect(decodeCity(JSON.parse(JSON.stringify(c)))).toEqual(c);});
  it('migrates v5 without changing existing systems or tile layout',()=>{const old:any=fixture();old.version=5;delete old.publicServices;for(const t of old.tiles){delete t.publicServices;delete t.publicFacility;}const before=structuredClone(old),c=decodeCity(old);expect(c.version).toBe(9);expect(c.tiles.map(t=>[t.building,t.road,t.zone,t.infrastructure,t.mobility])).toEqual(before.tiles.map((t:any)=>[t.building,t.road,t.zone,t.infrastructure,t.mobility]));expect(c.treasury).toBe(before.treasury);expect(c.publicServices.facilities).toHaveLength(0);});
  it('rejects invalid facility refs, overlapping footprints and malformed funding',()=>{const c=fixture();facility(c,'phc');const missing=structuredClone(c);missing.tiles[332].publicFacility='missing';expect(()=>decodeCity(missing)).toThrow();const bad=structuredClone(c);bad.publicServices.funding.education=300;expect(()=>decodeCity(bad)).toThrow();const duplicate=structuredClone(c);duplicate.publicServices.facilities.push({...duplicate.publicServices.facilities[0],id:'duplicate'});expect(()=>decodeCity(duplicate)).toThrow();});
  it('offline simulation exactly replays staffing, capacity, waste, fires and QoL',()=>{const c=fixture();facility(c,'fire-station');facility(c,'primary-school',14,8);triggerFire(c,332);const active=decodeCity(JSON.parse(JSON.stringify(c))),away=decodeCity(JSON.parse(JSON.stringify(c)));advance(active,20);const report=catchUp(away,20*TICK_MS);active.lastSimulatedTimestamp=20*TICK_MS;expect(away).toEqual(active);expect(report.firesContained).toBeGreaterThan(0);expect(report.wasteAfter).toBeGreaterThan(0);expect(report.qolAfter).not.toBe(report.qolBefore);});
});
