import { describe, expect, it } from 'vitest';
import { createCity, advance, applyTool, catchUp, TICK_MS, refreshCity } from '../shared/simulation/engine';
import { crimePressure, initializeSafety, lightingLevel, roadLightingDemand, triggerSafetyIncident, updateSafety } from '../shared/simulation/safety';
import { makeFacility, updatePublicServices } from '../shared/simulation/public-services';
import { invalidateRoadGraph } from '../shared/simulation/road-network';
import { createDistrict, togglePolicy, updateGovernance } from '../shared/simulation/governance';
import { decodeCity } from '../shared/simulation/save-format';
import { cityActivity } from '../shared/simulation/activity';
import { operateBusinesses } from '../shared/simulation/economy';
import { vehiclePlan } from '../client/game/activity-policy';
import { safetySummary, safetyInspector } from '../client/ui/safety-panels';
import { detectCityPulse } from '../client/ui/city-pulse';
import { publicServiceFixture } from '../shared/simulation/public-service-fixtures';

const home=10*32+12;
function fixture(){const c=createCity(0,731);for(const t of c.tiles){t.terrain='land';t.services.floodDepth=0;t.services.powerReliability=100;t.services.waterReliability=100;}return c;}
function police(c:ReturnType<typeof fixture>,kind:'police-post'|'police-station'|'area-command'='police-station',id=8*32+12){
  const f=makeFacility(c,id,kind);for(const id of f.tiles){const t=c.tiles[id];t.zone=null;t.building=null;t.road=false;t.infrastructure=null;t.publicFacility=f.id;}
  f.employeesAvailable=f.employeesRequired;c.publicServices.facilities.push(f);c.publicServices.revision++;updatePublicServices(c,false);updateSafety(c,false);return f;
}
describe('spatial prevention and road-aware safety',()=>{
  it('starts a small city without police without collapsing safety',()=>{const c=createCity();expect(c.safety.metrics.policeAccess).toBe(0);expect(c.safety.metrics.publicSafety).toBeGreaterThan(55);expect(c.safety.totalIncidents).toBe(0);});
  it('combines structural stresses and supports non-police recovery',()=>{const healthy={economicStress:0,employmentStress:5,housingStress:10,serviceStress:15,opportunity:70,community:85,visibility:80,patrol:0};const stressed={...healthy,employmentStress:85,housingStress:80,serviceStress:90,community:20,visibility:10};expect(crimePressure(stressed)).toBeGreaterThan(crimePressure(healthy)+25);});
  it('does not derive crime from informal tenure or income',()=>{const c=fixture();c.unemploymentRate=5;for(const t of c.tiles){t.mobility.accessibility=90;t.publicServices.education.quality=90;t.publicServices.healthcare.quality=90;t.publicServices.parks.quality=90;t.publicServices.waste.quality=90;t.roadClass=t.road?'major':null;c.governance.local[t.y*32+t.x].pressure=5;}
    updateSafety(c,false);const before=c.safety.local[home].crimePressure;c.tiles[home].building!.tenure='informal';c.governance.local[home].income=80000;updateSafety(c,false);expect(c.safety.local[home].crimePressure).toBe(before);expect(before).toBeLessThan(25);expect(c.safety.local[home].publicSafety).toBeGreaterThan(70);});
  it('places police through the existing paid public-service workflow and hires aggregate staff',()=>{const c=fixture(),treasury=c.treasury;expect(applyTool(c,12,8,'police-post')).toBe('');expect(c.treasury).toBe(treasury-8000000);expect(c.publicServices.publicJobs).toBe(12);advance(c,30);const f=c.publicServices.facilities[0];expect(f.employeesAvailable).toBeGreaterThan(0);expect(c.publicServices.employed).toBeLessThanOrEqual(c.employed);expect(c.expenses).toBeGreaterThan(f.monthlyOperatingCost);},30000);
  it('offers road-aware access and public jobs with real recurring costs',()=>{const c=fixture(),f=police(c);expect(c.publicServices.publicJobs).toBe(f.employeesRequired);expect(c.publicServices.costs.police).toBeGreaterThan(0);expect(c.safety.local[home].policeAccess).toBeGreaterThan(0);expect(c.safety.local[home].responseMinutes).toBeLessThan(60);});
  it('does not operate an unstaffed station',()=>{const c=fixture(),f=police(c);f.employeesAvailable=0;updatePublicServices(c,false);updateSafety(c,false);expect(f.effectiveCapacity).toBe(0);triggerSafetyIncident(c,home,'moderate');expect(c.safety.incidents[0].respondingUnit).toBeNull();});
  it('distinguishes disconnected areas even with citywide police capacity',()=>{const c=fixture();police(c);const remote=20*32+20;c.tiles[remote].road=true;c.tiles[remote].roadClass='local';invalidateRoadGraph(c);updateSafety(c,false);expect(c.safety.local[remote].policeAccess).toBe(0);expect(c.safety.local[remote].responseMinutes).toBe(60);});
  it('congestion increases response time and road recovery reverses it',()=>{const c=fixture();police(c);triggerSafetyIncident(c,home,'serious');const before=c.safety.incidents[0].responseTime;
    for(const t of c.tiles)if(t.road)t.mobility.congestion=95;invalidateRoadGraph(c);c.tick++;updateSafety(c);const delayed=c.safety.incidents[0].responseTime;expect(delayed).toBeGreaterThan(before);
    for(const t of c.tiles)if(t.road)t.mobility.congestion=0;invalidateRoadGraph(c);c.tick++;updateSafety(c);expect(c.safety.incidents[0].responseTime).toBeLessThan(delayed);});
  it('flooded road cuts dispatch rather than inventing radius access',()=>{const c=fixture();police(c);for(const t of c.tiles)if(t.road)t.services.floodDepth=95;invalidateRoadGraph(c);triggerSafetyIncident(c,home,'serious');expect(c.safety.incidents[0].respondingUnit).toBeNull();});
  it('police overload delays responses and reduces patrol',()=>{const c=fixture();police(c,'police-post');const patrol=c.safety.local[home].patrol;for(const t of c.tiles.filter(t=>t.building))triggerSafetyIncident(c,t.y*32+t.x,'serious');updateSafety(c,false);expect(c.safety.facilities[0].activeIncidents).toBeGreaterThan(1);expect(c.safety.local[home].patrol).toBeLessThan(patrol);expect(c.safety.incidents.at(-1)!.responseTime).toBeGreaterThan(c.safety.incidents[0].responseTime);police(c,'area-command',6*32+14);expect(c.safety.local[home].patrol).toBeGreaterThan(0);});
  it('funding has diminishing returns and cannot replace staffing',()=>{const c=fixture(),f=police(c);const baseline=f.effectiveCapacity;c.publicServices.funding.police=150;updatePublicServices(c,false);expect(f.effectiveCapacity/baseline).toBeLessThan(1.2);f.employeesAvailable=0;updatePublicServices(c,false);expect(f.effectiveCapacity).toBe(0);});
  it('lighting follows road hierarchy and real electricity',()=>{const c=fixture(),r=c.tiles[10*32+13];r.roadClass='dirt';const dirt=lightingLevel(c,c.tiles[home]);r.roadClass='major';expect(lightingLevel(c,c.tiles[home])).toBeGreaterThan(dirt);expect(roadLightingDemand(c,r)).toBeGreaterThan(0);r.services.powerReliability=0;expect(lightingLevel(c,c.tiles[home])).toBe(0);});
  it('outage reduces night safety and restoration improves it',()=>{const c=fixture();updateSafety(c,false);const before=c.safety.local[home].nightSafety;for(const t of c.tiles)t.services.powerReliability=0;c.tick++;updateSafety(c);expect(c.safety.local[home].nightSafety).toBeLessThan(before);for(const t of c.tiles)t.services.powerReliability=100;c.tick++;updateSafety(c);expect(c.safety.local[home].nightSafety).toBeCloseTo(before);});
  it('district prevention produces moderate spatial effects after the implementation delay',()=>{const c=fixture();createDistrict(c,[home],'Unity');togglePolicy(c,'community-safety',c.governance.districts[0].id);const initial=c.safety.local[home].crimePressure;for(let n=0;n<40;n++){c.tick++;updateGovernance(c);}updateSafety(c,false);expect(c.safety.local[home].crimePressure).toBeLessThan(initial);expect(c.safety.local[home].crimePressure).toBeGreaterThan(0);expect(c.governance.programCost).toBeGreaterThan(0);expect(c.safety.districts[c.governance.districts[0].id]).toBeDefined();});
  it('responds to pressure gradually instead of jumping between extremes',()=>{const c=fixture();const initial=c.safety.local[home].crimePressure;c.unemploymentRate=95;c.tick=5;updateSafety(c);expect(c.safety.local[home].crimePressure).toBeGreaterThan(initial);expect(c.safety.local[home].crimePressure-initial).toBeLessThan(15);});
  it('resolves unserved incidents and decays bounded local consequences',()=>{const c=fixture();triggerSafetyIncident(c,home,'serious');const shock=c.safety.local[home].shock;for(let n=0;n<15;n++){c.tick++;updateSafety(c);}expect(c.safety.incidents[0].status).toBe('resolved');expect(c.safety.local[home].shock).toBeLessThan(shock*.3);expect(c.safety.local[home].publicSafety).toBeGreaterThan(40);});
  it('deduplicates an active tile and keeps serious incidents actionable',()=>{const c=fixture();expect(triggerSafetyIncident(c,home,'serious')).toBe(true);expect(triggerSafetyIncident(c,home,'serious')).toBe(false);const p=detectCityPulse(c).find(p=>p.id===c.safety.incidents[0].id)!;expect(p.tileId).toBe(home);expect(p.overlay).toBe('police');expect(safetyInspector(c,c.tiles[home])).toContain('No reachable response');});
  it('night safety changes evening commerce without inventing businesses',()=>{const c=fixture(),id=14*32+14;const before=cityActivity(c,19).tiles[id].commercial;c.safety.local[id].eveningActivity=.65;expect(cityActivity(c,19).tiles[id].commercial).toBeLessThan(before);});
  it('persistent concerns reduce output modestly without shutting a business instantly',()=>{const c=fixture(),id=14*32+14;operateBusinesses(c);const before=c.tiles[id].building!.monthlyEconomicOutput;c.safety.local[id].commercialSafety=35;c.safety.local[id].shock=15;operateBusinesses(c);expect(c.tiles[id].building!.monthlyEconomicOutput).toBeLessThan(before);expect(c.tiles[id].building!.business!.closedAt).toBeNull();});
  it('only plans police representatives from an assigned incident or staffed patrol',()=>{const c=fixture(),visible=new Set(c.tiles.flatMap((t,id)=>t.road?[id]:[]));expect(vehiclePlan(c,cityActivity(c),visible,50).some(p=>p.mode==='police-car')).toBe(false);police(c);triggerSafetyIncident(c,home,'serious');const plans=vehiclePlan(c,cityActivity(c),visible,50).filter(p=>p.mode==='police-car');expect(plans.some(p=>p.key.startsWith(c.safety.incidents[0].id))).toBe(true);expect(plans.length).toBeLessThanOrEqual(2);});
  it('removes demolished station references before saving',()=>{const c=fixture(),f=police(c);triggerSafetyIncident(c,home,'serious');applyTool(c,f.location%32,Math.floor(f.location/32),'bulldoze');expect(()=>decodeCity(JSON.parse(JSON.stringify(c)))).not.toThrow();});
  it('migrates M6 saves while preserving old roads, population, money and timestamp',()=>{const c:any=fixture(),original=structuredClone(c);c.version=7;delete c.safety;delete c.publicServices.funding.police;delete c.publicServices.costs.police;delete c.publicServices.stats.police;for(const t of c.tiles)delete t.publicServices.police;for(const l of c.governance.local)for(const k of ['lighting','prevention','commercialPatrol','hubSafety'])delete l.effects[k];const loaded=decodeCity(c);expect(loaded.version).toBe(9);expect(loaded.population).toBe(original.population);expect(loaded.treasury).toBe(original.treasury);expect(loaded.lastSimulatedTimestamp).toBe(original.lastSimulatedTimestamp);expect(loaded.tiles.map(t=>t.road)).toEqual(original.tiles.map((t:any)=>t.road));expect(()=>decodeCity(JSON.parse(JSON.stringify(loaded)))).not.toThrow();});
  it('rejects malformed incident paths and non-finite safety fields',()=>{const c=fixture();triggerSafetyIncident(c,home);const corrupt=JSON.parse(JSON.stringify(c));corrupt.safety.incidents[0].response.path=[1,1000];expect(()=>decodeCity(corrupt)).toThrow('Safety');corrupt.safety.incidents=[];corrupt.safety.local[home].crimePressure=null;expect(()=>decodeCity(corrupt)).toThrow('Safety');});
  it('offline incidents and recovery match the same seeded online interval',()=>{const a=fixture();police(a);triggerSafetyIncident(a,home,'serious');const b=decodeCity(JSON.parse(JSON.stringify(a)));advance(a,120);const report=catchUp(b,120*TICK_MS);expect(b.safety).toEqual(a.safety);expect(report.safetyIncidents).toBe(b.safety.totalIncidents-1);expect(report.safetyAfter).toBe(b.safety.metrics.publicSafety);expect(safetySummary(b)).toContain('Structural crime pressure');},30000);
  it('organic incident categories follow actual building and street use',()=>{const c=publicServiceFixture(100000);initializeSafety(c);for(let n=0;n<30;n++){c.tick++;updateSafety(c);}expect(c.safety.totalIncidents).toBeGreaterThan(0);for(const i of c.safety.incidents){if(i.type==='commercial')expect(c.tiles[i.location].zone).toBe('commercial');if(i.type==='public-space')expect(c.tiles[i.location].road).toBe(true);if(i.type==='vehicle')expect(c.tiles[i.location].road||c.tiles[i.location].zone==='commercial').toBe(true);}},30000);
  it('100k and 500k fixtures use bounded aggregates rather than people',()=>{for(const population of [100000,500000] as const){const c=publicServiceFixture(population);initializeSafety(c);expect(c.population).toBe(population);expect(c.safety.local).toHaveLength(1024);for(let n=0;n<30;n++){c.tick++;updateSafety(c);}expect(c.safety.incidents.length).toBeLessThanOrEqual(120);expect(c.safety.metrics.publicSafety).toBeGreaterThan(20);advance(c,1);expect(Number.isFinite(c.treasury)).toBe(true);}},30000);
  it('twenty years remain recoverable with bounded history, incidents and costs',()=>{const c=fixture();police(c);advance(c,7200);expect(c.safety.incidents.length).toBeLessThanOrEqual(384);expect(c.safety.history.length).toBeLessThanOrEqual(240);expect(c.safety.totalIncidents).toBeGreaterThan(0);expect(c.safety.metrics.crimePressure).toBeGreaterThanOrEqual(5);expect(c.safety.metrics.crimePressure).toBeLessThan(85);expect(c.safety.metrics.publicSafety).toBeGreaterThan(25);expect(c.publicServices.costs.police).toBeLessThan(4000000);expect(c.safety.incidents.every(i=>i.status==='resolved'||c.tick-i.startTime<8)).toBe(true);expect(()=>decodeCity(JSON.parse(JSON.stringify(c)))).not.toThrow();},240000);
});
