// Developer and QA tools. main.ts only calls this inside `if (import.meta.env.DEV)`, so production
// builds drop the module and players never see simulation-mutating controls.
import type { City, Overlay } from '../../shared/types/city';
import type { DebugAction } from '../../shared/simulation/debug';
import type { InfrastructureDebug } from '../../shared/simulation/infrastructure-debug';
import { TRANSIT_OVERLAYS } from '../../shared/simulation/transit-config';
import { MOBILITY_DEBUG } from '../../shared/simulation/mobility-debug';
import { transitReportHtml } from './transit-panels';
import { SAFETY_OVERLAYS } from './safety-panels';
import { GOVERNANCE_OVERLAYS } from './governance-panels';
import { activityTime } from './living-panels';

export interface DevPanelContext { city: City; debugTarget: number | null; transitReportOpen: boolean; activityHourOverride: number | null }
export function developerSettingsHtml({ city, debugTarget, transitReportOpen, activityHourOverride }: DevPanelContext) {
  let html = '';
  const transitDebugHtml=`<h3>Transit diagnostics</h3>${TRANSIT_OVERLAYS.map(o=>`<button data-overlay="${o}">${o}</button>`).join('')}${['demand','crowding','congestion','flood','cache','report'].map(a=>`<button data-transit-debug="${a}">${a}</button>`).join('')}${transitReportOpen?transitReportHtml(city):''}`;
  const debugTools: [DebugAction, string][] = [['demand-residential', 'Increase Residential Demand'], ['demand-commercial', 'Increase Commercial Demand'], ['demand-industrial', 'Increase Industrial Demand'], ['development', 'Force Development Tick'], ['complete', 'Complete Construction'], ['upgrade', 'Force Building Upgrade'], ['close-business', 'Force Business Closure'], ['unemployment', 'Create Unemployment'], ['boost', 'Boost Economy'], ['month', 'Advance 1 Month'], ['year', 'Advance 1 Year']];
  const infraTools: [InfrastructureDebug, string][] = [['light-rain', 'Trigger Light Rain'], ['heavy-rain', 'Trigger Heavy Rain'], ['extreme-rain', 'Trigger Extreme Rain'], ['end-rain', 'End Rain'], ['power-demand', 'Set Power Demand +25%'], ['plant-failure', 'Cause Power Plant Failure'], ['restore-power', 'Restore Power Infrastructure'], ['water-demand', 'Set Water Demand +25%'], ['water-shortage', 'Cause Water Shortage'], ['flood-tile', 'Flood Selected Tile'], ['clear-floods', 'Clear Flooding'], ['drainage-capacity', 'Set Drainage Capacity · 1× / 2×'], ['damage-infrastructure', 'Damage Infrastructure'], ['repair-infrastructure', 'Repair Infrastructure']];
  html += `<details${transitReportOpen?' open':''}><summary>Developer controls</summary>${transitDebugHtml}<div class="debug-tools">${debugTools.map(([action, label]) => `<button class="secondary" data-debug="${action}">${label}</button>`).join('')}${MOBILITY_DEBUG.map(action => `<button class="secondary" data-mobility-debug="${action}">${action}</button>`).join('')}<button data-mobility-view="od">Show OD Demand</button><button data-mobility-view="graph">Show Road Graph</button><button data-mobility-view="capacity">Show Segment Capacity</button><button data-action="vehicle-count">Show Representative Vehicle Count</button>${(['bounds','anchors','depth','lod','shadows','props','vegetation','weather'] as const).map(v => `<button data-graphics-toggle="${v}">Toggle ${v === 'bounds' ? 'tile bounds' : v === 'anchors' ? 'object anchors' : v === 'depth' ? 'depth order' : v === 'lod' ? 'LOD level' : v === 'weather' ? 'weather effects' : v}</button>`).join('')}<button data-action="graphics-count">Show sprite / visible object count</button><button data-action="graphics-count">Show texture atlas usage / performance</button>${infraTools.map(([action, label]) => `<button class="secondary" data-infra-debug="${action}">${label}</button>`).join('')}${(['development', 'land-value', 'occupancy', 'power', 'water', 'drainage', 'flood-risk'] as Overlay[]).map(o => `<button class="secondary" data-overlay="${o}">Show ${o.replaceAll('-', ' ')} overlay</button>`).join('')}<button class="secondary" data-overlay="none">Clear infrastructure overlays</button></div><p class="hint">Flood Selected Tile uses the last inspected tile${debugTarget === null ? ' (none yet)' : ` (${debugTarget % city.size}, ${Math.floor(debugTarget / city.size)})`}. These actions change the saved simulation.</p></details>`;
  html+=`<details><summary>Safety diagnostics</summary><div class="debug-tools">${SAFETY_OVERLAYS.map(o=>`<button data-overlay="${o}">Show ${o.replaceAll('-',' ')}</button>`).join('')}${['minor','moderate','serious'].map(v=>`<button data-safety-debug="${v}">Force ${v} incident at selected tile</button>`).join('')}</div><p>Seeded incident generation · ${city.safety.totalIncidents} total · ${city.safety.seriousIncidents} serious · ${city.safety.resolvedIncidents} resolved · ${city.safety.metrics.incidents30Days} during the last 30 days.</p></details>`;
  html+=`<details><summary>Governance diagnostics</summary><div class="debug-tools">${GOVERNANCE_OVERLAYS.map(o=>`<button data-overlay="${o}">${o.replaceAll('-',' ')}</button>`).join('')}<button data-governance-tab="Housing">Housing supply / affordability / income</button><button data-governance-tab="Budget">Spending and maintenance</button></div></details>`;
  html+=`<details><summary>Public service diagnostics</summary><div class="debug-tools">${["education-demand","education-capacity","healthcare-demand","healthcare-capacity","fire-response","waste-generation","waste-collection","park-access","quality-of-life","accessibility","clear"].map(v=>`<button data-public-view="${v}">Show ${v.replaceAll("-"," ")}</button>`).join("")}${['education','healthcare','fire','waste','parks','quality-of-life'].map(o=>`<button data-overlay="${o}">Show ${o}</button>`).join('')}${[['fire','Trigger selected building fire'],['waste','Increase selected waste backlog'],['staff','Fill facility staff for testing'],['repair','Repair facilities'],['access','Show cached service access diagnostics']].map(([a,n])=>`<button data-public-debug="${a}">${n}</button>`).join('')}</div><p class="hint">Education shows seats, healthcare shows visit demand, fire shows response reach, waste shows collection and parks show recreation. Inspector exposes capacity separately.</p></details>`;
  html += `<details><summary>Living city diagnostics</summary><label class="budget-label">Activity hour <select id="activity-hour"><option value="auto" ${activityHourOverride === null ? 'selected' : ''}>Simulation clock</option>${[0,6,8,13,17,20].map(h => `<option value="${h}" ${activityHourOverride === h ? 'selected' : ''}>${activityTime(h)}</option>`).join('')}</select></label><div class="debug-tools">${[['activity','Show activity scores'],['network','Show pedestrian network'],['od','Show commuter OD'],['traffic','Show vehicle flow'],['mobility','Show transit demand'],['neighborhoods','Show neighborhood boundaries'],['business','Show business health'],['markets','Show market attraction'],['informal','Show informal housing pressure']].map(([view,label])=>`<button data-living-view="${view}">${label}</button>`).join('')}<button data-action="living-count">Representative agent diagnostics</button><button data-living-view="clear">Clear living diagnostics</button></div></details>`;
  return `<section class="developer-tools"><h3>Developer tools · development build only</h3>${html}</section>`;
}
