import { transitSummary } from './transit-panels';
import { safetySummary } from './safety-panels';
import type { City, Tile } from '../../shared/types/city';
import { POLICIES, GOVERNANCE, OBJECTIVES } from '../../shared/simulation/governance-config';
import { localGovernance, objectiveProgress } from '../../shared/simulation/governance';
import { compactMoney, escapeHtml } from './panels';

export const GOVERNANCE_TABS=['Overview','Budget','Taxes','Policies','Districts','Housing','Development','Safety'];
export const GOVERNANCE_OVERLAYS=['affordability','environment','development-pressure','housing-pressure','cost-of-living','migration-pressure','district-policy','infrastructure-condition'];
const pct=(n:number)=>`${Math.round(n)}%`;
const row=(label:string,value:string)=>`<div><dt>${escapeHtml(label.replace(/([A-Z])/g,' $1'))}</dt><dd>${value}</dd></div>`;
function chart(city:City,key:'population'|'jobs'|'rent'|'affordability'|'qualityOfLife'|'revenue'|'expenses'|'congestion',label:string){
  const samples=city.governance.history.slice(-36);if(samples.length<2)return '';
  const values=samples.map(s=>s[key]),min=Math.min(...values),span=Math.max(1,Math.max(...values)-min);
  const points=values.map((v,i)=>`${8+i/(values.length-1)*260},${58-(v-min)/span*46}`).join(' ');
  return `<figure class="governance-chart"><figcaption>${escapeHtml(label)} · last ${samples.length} months</figcaption><svg viewBox="0 0 280 70" role="img" aria-label="${escapeHtml(label)} trend"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="2"/></svg><small>${Math.round(values[0]).toLocaleString()} → ${Math.round(values.at(-1)!).toLocaleString()}</small></figure>`;
}
function policyList(city:City,districtId:string|null){return `<p class="hint">Seven-day activation; effects ramp over 21 days. Review decisions after 30 days. City and district copies of the same policy do not stack.</p>${POLICIES.map(def=>{const p=city.governance.policies.find(p=>p.id===def.id&&p.districtId===districtId);return `<article class="governance-card"><h3>${escapeHtml(def.name)}</h3><p>${escapeHtml(def.description)}</p><small>${escapeHtml(def.requirements)}<br>${compactMoney(def.cost)}/resident/month plus administration, at full implementation.</small><button data-policy="${def.id}" data-policy-scope="${districtId??''}" aria-pressed="${p?.enabled??false}">${p?.enabled?'Disable':'Enable'}${p?` · ${pct(p.strength*100)} implemented`:''}</button></article>`;}).join('')}`;}
export function governanceInspector(city:City,tile:Tile){const l=localGovernance(city,tile);if(!l)return '';const d=city.governance.districts.find(d=>d.id===l.districtId);return `<h3>Housing & governance</h3><dl>${row('District',escapeHtml(d?.name??'Unassigned'))}${row('Indicative monthly household rent',compactMoney(l.rent))}${row('Housing affordability',pct(l.affordability))}${row('Cost-of-living burden',pct(l.costOfLiving))}${row('Environmental quality',pct(l.environment))}${row('Development pressure',pct(l.pressure))}</dl><p class="hint">Game estimates, not real housing prices.</p>${d?`<button data-district="${d.id}">Govern district</button>`:''}`;}
export function governancePanel(city:City,tab:string,districtId:string|null){
  const g=city.governance,h=g.housing;
  let html=`<div class="service-tabs">${GOVERNANCE_TABS.map(t=>`<button data-governance-tab="${t}" aria-pressed="${tab===t}">${t}</button>`).join('')}</div>`;
  if(tab==='Overview'){
    html+=`<p>Govern the conditions for growth. Private development remains autonomous.</p><dl>${Object.entries(g.health).map(([k,v])=>row(k.charAt(0).toUpperCase()+k.slice(1),pct(v))).join('')}</dl><h3>City profile</h3><p>Strengths: ${Object.entries(g.health).filter(([,v])=>v>=70).map(([k])=>escapeHtml(k)).join(', ')||'still emerging'}.</p><label>Planning objective <select data-objective><option value="">No objective</option>${Object.entries(OBJECTIVES).map(([id,name])=>`<option value="${id}" ${g.objective===id?'selected':''}>${name}</option>`).join('')}</select></label>${g.objective?`<p>${OBJECTIVES[g.objective]}: ${pct(objectiveProgress(city,g.objective))}. Guidance based on current outcomes; no rewards or forced projects.</p>`:''}<h3>Urban challenges</h3>`;
    const active=g.challenges.filter(c=>!c.resolved);html+=active.length?active.map(c=>`<article class="governance-card"><strong>${escapeHtml(c.title)} · ${c.severity}</strong><p>${escapeHtml(c.description)}</p><small>Why: ${c.causes.map(escapeHtml).join('; ')}.</small><ul>${c.responses.map(r=>`<li>${escapeHtml(r)}</li>`).join('')}</ul><button data-challenge="${escapeHtml(c.id)}">Investigate</button></article>`).join(''):'<p>No major active challenges.</p>';
    html+=`<h3>Approximate 90-day outlook</h3><dl>${row('Population',g.forecast.population.toLocaleString())}${row('Housing need',`${g.forecast.housingNeed} units`)}${row('Electricity demand',`${g.forecast.powerDemand.toFixed(2)} MW`)}${row('Water demand',`${g.forecast.waterDemand.toFixed(1)} units`)}</dl><p class="hint">Trend estimates, not predictions. Future policies, construction and weather can change them.</p>`;
    if(g.forecast.housingNeed>h.units)html+='<p>Forecast housing needs exceed current capacity.</p>';
    if(g.forecast.powerDemand>city.infrastructure.power.supply)html+='<p>Forecast electricity demand exceeds current supply.</p>';
    if(g.forecast.waterDemand>city.infrastructure.water.production)html+='<p>Forecast water demand exceeds current production.</p>';
  }else if(tab==='Safety'){html+=safetySummary(city);
  }else if(tab==='Budget'){
    html+=transitSummary(city);
    html+=`<dl>${row('Treasury',compactMoney(city.treasury))}${Object.entries(city.taxes).map(([k,v])=>row(`${k} tax`,compactMoney(v))).join('')}${row('Other revenue / fares',compactMoney(city.mobility.costs.fares))}${row('Monthly revenue',compactMoney(city.income))}${Object.entries({...city.infrastructure.costs,...city.publicServices.costs}).map(([k,v])=>row(k,compactMoney(v))).join('')}${row('Bus operations',compactMoney(city.mobility.costs.buses))}${row('Route administration',compactMoney(city.mobility.costs.administration))}${row('Governance programmes',compactMoney(g.programCost))}${row('Monthly expenses',compactMoney(city.expenses))}${row('Monthly balance',compactMoney(city.income-city.expenses))}${row('Projected annual balance',compactMoney(g.forecast.annualBalance))}</dl><h3>Infrastructure priorities</h3><p class="hint">Priority adjusts existing maintenance funding by −15 or +20 percentage points. It cannot extend network coverage.</p>${Object.entries(g.priorities).map(([k,v])=>`<label class="budget-label">${k}<select data-priority="${k}">${['low','standard','high'].map(p=>`<option ${v===p?'selected':''}>${p}</option>`).join('')}</select></label>`).join('')}<button data-action="economy">Existing funding budgets</button>${chart(city,'revenue','Revenue')}${chart(city,'expenses','Expenses')}`;
  }else if(tab==='Taxes'){
    html+='<p>Higher rates can raise revenue but reduce household spending, investment and business profitability. Effects phase in gradually.</p>';
    html+=(['residential','commercial','industrial'] as const).map(z=>`<label class="budget-label">${z} · effective ${g.taxes.effective[z].toFixed(2)}%<input aria-label="${z} tax target" data-tax="${z}" type="number" min="${GOVERNANCE.taxes[z].min}" max="${GOVERNANCE.taxes[z].max}" step="${z==='residential'?'.05':'.5'}" value="${g.taxes.target[z]}"/></label><small>${z==='residential'?'Monthly occupied property value':'Monthly business output; existing property component retained'}. Next review: day ${Math.max(city.tick,g.taxes.changedAt[z]+30)}.</small>`).join('');
  }else if(tab==='Policies'){html+=`<label>Policy scope <select data-policy-district><option value="">Citywide</option>${g.districts.map(d=>`<option value="${d.id}" ${districtId===d.id?'selected':''}>${escapeHtml(d.name)}</option>`).join('')}</select></label>${policyList(city,districtId)}`;
  }else if(tab==='Districts'){
    html+='<p>Adopt an organic neighborhood or select two corners on the map. District boundaries govern land; neighborhood identities remain intact.</p><button data-district-draw>Select area on map</button>';
    html+=city.clusters.map(c=>`<button data-adopt="${c.id}">Adopt ${escapeHtml(c.name)}</button>`).join('');
    html+=`<h3>Compare districts</h3><div class="governance-table"><table><thead><tr><th>District</th><th>Residents</th><th>Afford.</th><th>QoL</th><th>Jobs / workers</th></tr></thead><tbody>${g.districts.map(d=>`<tr><td><button data-district="${d.id}">${escapeHtml(d.name)}</button></td><td>${d.metrics.population}</td><td>${pct(d.metrics.affordability)}</td><td>${pct(d.metrics.qualityOfLife)}</td><td>${d.metrics.jobHousingBalance.toFixed(1)}</td></tr>`).join('')}</tbody></table></div>`;
    const d=g.districts.find(d=>d.id===districtId);if(d){html+=`<h3>${escapeHtml(d.name)}</h3><label>District name <input data-district-name="${d.id}" value="${escapeHtml(d.name)}" maxlength="60"/></label><button data-district-focus="${d.id}">Focus boundary</button><dl>${Object.entries(d.metrics).map(([k,v])=>row(k,k==='rent'?compactMoney(v):Math.round(v).toLocaleString())).join('')}</dl>${city.safety.districts[d.id]?`<h3>District safety</h3><dl>${Object.entries(city.safety.districts[d.id]).map(([k,v])=>row(k,v.toFixed(1))).join('')}</dl>`:''}<button data-district-policy="${d.id}">District policies / community upgrading</button>${d.metrics.informalResidents?`<h3>Community strategy</h3><button data-policy="community-upgrade" data-policy-scope="${d.id}">Upgrade community services</button><button data-policy="integration" data-policy-scope="${d.id}">Integrate livelihoods & housing</button><button data-policy="formalization" data-policy-scope="${d.id}">Supported formalization</button><p>Programmes implement gradually and require real road and utility access.</p><p>Clearance displaces up to ${d.metrics.informalResidents} residents. Provide replacement housing first.</p><button data-clear-community="${d.id}">Clear informal housing…</button>`:''}`;}
  }else if(tab==='Housing'){
    html+=`<dl>${row('Households',city.households.toLocaleString())}${row('Housing units',h.units.toLocaleString())}${row('Occupied / vacant',`${h.occupied} / ${h.vacant}`)}${row('Household demand',h.demand.toLocaleString())}${row('Housing pressure',pct(h.pressure))}${row('Indicative rent / household',compactMoney(h.averageRent))}${row('Affordability',pct(h.affordability))}${row('Overcrowding pressure',pct(h.overcrowding))}${row('Displaced residents',String(h.displacedResidents))}${row('Rehoused / departed',`${h.rehoused} / ${h.departed}`)}${row('Cost-of-living burden',pct(h.costOfLiving))}${row('Income dispersion indicator',pct(h.inequality))}</dl><p class="hint">Aggregate estimates from existing capacity, earnings, jobs and land values. Income dispersion is not a real Gini coefficient. Five income bands: ${h.incomeBands.map(Math.round).join(' / ')} residents.</p><button data-overlay="affordability">Affordability map</button><button data-overlay="housing-pressure">Housing pressure</button>${chart(city,'rent','Indicative rent')}${chart(city,'affordability','Affordability')}${chart(city,'population','Population')}${chart(city,'jobs','Jobs')}`;
  }else if(tab==='Development'){
    html+=`<p>Policies guide private investment; they do not place buildings or bypass demand, capacity, construction, utilities or services.</p><div class="debug-tools">${GOVERNANCE_OVERLAYS.map(o=>`<button data-overlay="${o}">${o.replaceAll('-',' ')}</button>`).join('')}</div>${chart(city,'qualityOfLife','Quality of life')}${chart(city,'congestion','Congestion')}`;
  }
  return html;
}
