import { transitPlanningPanel, transitSummary } from './transit-panels';
import type { City, Tile } from '../../shared/types/city';
import { ROADS } from '../../shared/simulation/road-network';
import { compactMoney, escapeHtml } from './panels';
export function mobilitySummary(city: City) {
  const s = city.mobility.stats;
  return `<dl><div><dt>Daily trips</dt><dd>${Math.round(s.dailyTrips).toLocaleString()}</dd></div><div><dt>Average commute</dt><dd>${s.averageCommute.toFixed(1)} min</dd></div><div><dt>Traffic speed</dt><dd>${s.averageSpeed.toFixed(1)} km/h</dd></div><div><dt>Congestion</dt><dd>${Math.round(s.congestion)}%</dd></div><div><dt>Job accessibility</dt><dd>${Math.round(s.jobAccessibility)}%</dd></div><div><dt>Shared transport coverage</dt><dd>${Math.round(s.sharedCoverage)}%</dd></div><div><dt>Shared transport use</dt><dd>${Math.round(s.sharedUsage)}%</dd></div></dl><div class="mode-share">${Object.entries(s.modes).map(([mode, trips]) => `<span><b>${mode}</b> ${Math.round(trips).toLocaleString()} · ${(trips/Math.max(1,s.dailyTrips)*100).toFixed(1)}%</span>`).join('')}</div>`;
}
export function transportPanel(city: City, tab: string, selectedRoute: string | null) {
  if(['bus','brt','network'].includes(tab))return transitPlanningPanel(city,tab,selectedRoute);
  const tabs = `<div class="transport-tabs">${['overview', 'roads', 'informal', 'bus', 'brt', 'network'].map(t => `<button data-transport-tab="${t}" aria-pressed="${tab === t}">${t}</button>`).join('')}</div>`;
  const routes = city.mobility.routes.filter(r => tab === 'bus' ? r.mode === 'bus' : r.mode !== 'bus');
  const cards = routes.map(r => `<button class="route-card" data-route="${escapeHtml(r.id)}"><small>${r.formalized ? 'Recognized' : 'Organic informal'} ${r.mode}</small><b>${escapeHtml(r.originName)} ↔ ${escapeHtml(r.destinationName)}</b><span>${Math.round(r.ridership)} daily riders · ${r.vehicles} vehicles · ${Math.round(r.reliability)}% reliability</span></button>`).join('');
  const route = city.mobility.routes.find(r => r.id === selectedRoute);
  const detail = route ? `<section class="route-detail"><h3>${escapeHtml(route.originName)} ↔ ${escapeHtml(route.destinationName)}</h3><dl>${Object.entries({ Type: `${route.formalized ? 'Formalized' : 'Informal'} ${route.mode}`, 'Daily demand': Math.round(route.demand), 'Daily ridership': Math.round(route.ridership), Vehicles: route.vehicles, 'Passenger capacity / day': route.capacity, 'Average journey': `${route.minutes.toFixed(1)} min`, 'Average speed': `${route.averageSpeed.toFixed(1)} km/h`, Reliability: `${Math.round(route.reliability)}%`, 'Congestion contribution': `${Math.round(route.congestionImpact)} vehicle equivalents/day`, Profitability: `${Math.round(route.profitability)}%`, 'Operator balance / day': compactMoney(route.netProfit), 'Route age': `${route.age} days`, Frequency: `${Math.max(1, Math.round(route.minutes * 2 / route.vehicles))} min headway` }).map(([k, v]) => `<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><button data-route-focus="${escapeHtml(route.id)}">Find corridor on map ↗</button>${route.mode === 'bus' ? `<div class="settings-actions"><button data-fleet="1">Add bus · ₦12M</button><button data-fleet="-1">Withdraw bus</button><button data-bus-suspend>${route.suspended ? 'Resume' : 'Suspend'} service</button></div>` : !route.formalized ? `<button class="primary" data-formalize="${escapeHtml(route.id)}">Formalize · ${compactMoney(2000000 + route.path.length * 30000)}</button><p class="hint">Designated stops and route standards improve reliability and boarding efficiency. Private operators remain. Monthly administration applies.</p>` : '<p>Recognized corridor with designated boarding points.</p>'}</section>` : '';
  if (tab === 'overview') return tabs + transitSummary(city) + mobilitySummary(city) + `<p>Movement comes from homes, jobs and shopping. Short journeys can be walked; private Keke and Danfo operators respond to repeated demand.</p><button data-overlay="traffic">Traffic overlay</button><button data-overlay="mobility">Routes & hubs overlay</button><h3>Major daily travel flows</h3>${[...city.mobility.flows].sort((a, b) => b.trips - a.trips).slice(0, 8).map(f => `<button class="route-card" data-flow="${escapeHtml(f.id)}"><b>${escapeHtml(f.originName)} → ${escapeHtml(f.destinationName)}</b><span>${f.purpose} · ${Math.round(f.trips)} trips · ${f.minutes.toFixed(1)} min</span></button>`).join('') || '<p>Occupied homes and operating businesses generate trips.</p>'}<h3>Public transport budget / month</h3><p>Bus operations ${compactMoney(city.mobility.costs.buses)} · fares ${compactMoney(city.mobility.costs.fares)} · corridor administration ${compactMoney(city.mobility.costs.administration)}</p>`;
  if (tab === 'roads') return tabs + `<p>Upgrade a road in place. Wider roads cost more to build and maintain; dirt roads suffer during rain.</p>${Object.entries(ROADS).map(([k, d]) => `<button class="tool" data-tool="${k === 'local' ? 'road' : k === 'dirt' ? 'dirt-road' : k === 'major' ? 'major-road' : k}"><div><b>${d.name}</b><small>${compactMoney(d.cost)} · ${d.capacity} vehicles/hour · ${d.speed} km/h · upkeep ${compactMoney(d.upkeep)}/month</small></div></button>`).join('')}`;
  return tabs + (tab === 'bus' ? `<p>Select connected roads: start, optional waypoints, then end. Two buses cost ₦24M plus ₦300K per selected stop; operations cost ₦3.6M/month before fares.</p><button class="primary" data-action="bus-build">Plan bus service</button>` : '<p>Private operators open, grow and withdraw according to actual passenger demand and profitability. Inspect a corridor to govern it.</p>') + detail + cards + (!routes.length ? `<p>No ${tab === 'bus' ? 'public bus' : 'informal'} routes yet.</p>` : '');
}
export function mobilityInspector(city: City, t: Tile) {
  const m = t.mobility, flow = city.mobility.flows.find(f => f.id === m.majorFlow);
  return `<h3>Mobility</h3><dl>${(t.road ? [['Road class', ROADS[t.roadClass ?? 'local'].name], ['Daily trips', Math.round(m.dailyTrips)], ['Capacity / peak hour', `${Math.round(m.effectiveCapacity)} / ${m.capacity} vehicles`], ['Average speed', `${m.speed.toFixed(1)} km/h`], ['Congestion', `${Math.round(m.congestion)}%`]] : [['Job accessibility', `${Math.round(m.accessibility)}%`], ['Passing customers / stop activity', Math.round(m.footTraffic)], ['Nearby congestion', `${Math.round(m.congestion)}%`]]).map(([k, v]) => `<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>${flow ? `<p>Major flow: ${escapeHtml(flow.originName)} → ${escapeHtml(flow.destinationName)}</p>` : ''}${city.mobility.routes.filter(r => r.path.includes(t.y * city.size + t.x)).map(r => `<button data-route="${escapeHtml(r.id)}">Inspect ${r.mode} corridor ↗</button>`).join('')}`;
}
