import type { City, Tile, OfflineReport } from '../../shared/types/city';
import { attractiveness } from '../../shared/simulation/development';

export const escapeHtml=(text:string)=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const money=(value:number)=>`₦${Math.round(value).toLocaleString('en-NG')}`;
export const compactMoney=(value:number)=>`₦${new Intl.NumberFormat('en-NG',{notation:'compact',maximumFractionDigits:1}).format(value)}`;
const percent=(value:number)=>`${Math.round(value)}%`;
const row=(label:string,value:string|number)=>`<div><dt>${escapeHtml(label)}</dt><dd>${value}</dd></div>`;
const progress=(value:number)=>`<div class="progress"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div>`;
export function inspectorHtml(city:City,t:Tile){
  const b=t.building,check=attractiveness(city,t);
  let html=`<p>${t.zone??t.terrain} · Tile ${t.x}, ${t.y}</p><dl>${row('Land value',`${Math.round(t.landValue)} / 100`)}</dl>`;
  if(b){html+=`<h3>${escapeHtml(b.name)}</h3><p>${escapeHtml(b.subtype)} · ${b.type} · Level ${b.level}${b.abandoned?' · Abandoned':''}</p>`;
    if(b.constructionState!=='complete')html+=`<h3>${b.constructionState.replaceAll('-',' ')} · ${percent(b.constructionProgress)}</h3>${progress(b.constructionProgress)}`;
    html+=`<dl>${b.type==='residential'?row('Residents',`${b.occupants} / ${b.maximumOccupancy}`):row('Employees',`${b.jobs} / ${b.maximumJobs}`)}${row('Property value',compactMoney(b.propertyValue))}${row('Age',`${(b.age/360).toFixed(1)} years`)}${row('Satisfaction',percent(b.satisfaction))}${row('Tax contribution / month',compactMoney(b.taxContribution))}</dl>`;
    if(b.business)html+=`<h3>Business activity</h3><dl>${row('State',escapeHtml(b.business.state))}${row('Profitability score',`${b.business.profitability} / 100`)}${row('Monthly output',compactMoney(b.monthlyEconomicOutput))}${row('Operating costs',compactMoney(b.business.operatingCost))}${row('Net profit / month',compactMoney(b.business.netProfit))}</dl><p class="hint">Profitability 50 is break-even. Hiring is gradual, not instant.</p>`;
    if(!b.abandoned&&b.openedAt!==null)html+=`<h3>Private upgrade · ${percent(b.upgradeProgress)}</h3>${progress(b.upgradeProgress)}<p class="hint">Requires occupancy ≥78%, age, demand, established neighbours and sufficient land value. Citizens decide when to rebuild.</p>`;
  }
  if(t.zone){html+=`<h3>Development attractiveness · ${check.score} / 100</h3><p>${escapeHtml(check.reason)}</p><ul class="factors">${check.factors.map(f=>`<li class="${f.value<0?'negative':'positive'}"><span>${f.value>=0?'+':'−'}${Math.abs(f.value)}</span>${escapeHtml(f.label)}</li>`).join('')}</ul>`;
    if(!b)html+=`<p class="construction-status">${city.developmentQueue.some(e=>e.tileId===t.y*city.size+t.x)?'In the development queue':'Developer interest'} · ${percent(t.progress)}</p>${progress(t.progress)}<p class="hint">At most three active construction sites. Higher-scoring parcels start first; zoning is a plan, not a building order.</p>`;
  }else if(t.road)html+='<p>Roads provide access to adjacent zoned parcels. Major flooding temporarily blocks access.</p>';
  const cluster=city.clusters.find(c=>c.id===t.clusterId);if(cluster)html+=`<p class="hint">Emerging neighbourhood: ${escapeHtml(cluster.name)} · ${cluster.tileIds.length} developed parcels.</p>`;
  return html;
}
export function demandHtml(city:City){return `<div class="demand-detail">${(['residential','commercial','industrial'] as const).map(zone=>`<div class="${zone}"><b>${zone}</b><strong>${city.demand[zone]}</strong>${progress(city.demand[zone])}</div>`).join('')}</div>`;}
export function statisticsHtml(city:City,lastReturn:OfflineReport|null){
  return `${demandHtml(city)}<div class="overlay-buttons" aria-label="Data overlays"><button data-overlay="none">Normal</button><button data-overlay="land-value">Land value</button><button data-overlay="development">Development</button><button data-overlay="occupancy">Occupancy</button></div><dl>${row('Population',city.population.toLocaleString())}${row('Population change / day',`${city.growth>=0?'+':''}${city.growth}`)}${row('Households',city.households.toLocaleString())}${row('Housing capacity',city.housingCapacity.toLocaleString())}${row('Occupied housing',city.occupiedHousing.toLocaleString())}${row('Vacant housing',city.vacantHousing.toLocaleString())}${row('Housing vacancy',percent(city.vacantHousing/Math.max(1,city.housingCapacity)*100))}${row('Total jobs',city.jobs.toLocaleString())}${row('Workforce',city.workforce.toLocaleString())}${row('Employed',city.employed.toLocaleString())}${row('Unemployed',city.unemployed.toLocaleString())}${row('Unemployment',percent(city.unemploymentRate))}${row('Purchasing power',`${Math.round(city.purchasingPower)} / 100`)}${row('Average land value',`${Math.round(city.averageLandValue)} / 100`)}${row('City satisfaction',percent(city.satisfaction))}${row('Monthly revenue',compactMoney(city.income))}${row('Monthly expenses',compactMoney(city.expenses))}${row('Monthly balance',compactMoney(city.income-city.expenses))}${row('Queued parcels',city.developmentQueue.length)}${row('Active sites',city.tiles.filter(t=>t.building&&t.building.constructionState!=='complete').length)}</dl>${city.population>=1000?'<p>Your first 1,000 residents have arrived. Keep planning.</p>':'<p>First goal: 1,000 residents. Provide space for both homes and employment.</p>'}${progress(city.population/10)}<h3>Population · recent months</h3><div class="trend" aria-label="Monthly population history">${city.trends.slice(-18).map(s=>`<span title="Day ${s.tick}: ${s.population} residents" style="height:${Math.max(4,s.population/Math.max(1,...city.trends.slice(-18).map(t=>t.population))*100)}%"></span>`).join('')}</div><p class="hint">${city.trends.length?`${city.trends[0].population} → ${city.population} residents. History samples are retained for up to 120 months.`:'Monthly trend history starts after 30 city days.'}</p>${lastReturn?'<button class="secondary" data-action="last-return">Last return summary</button>':''}<h3>City journal</h3><ul id="journal"></ul>`;
}
export function offlineHtml(report:OfflineReport){
  const minutes=Math.floor(report.awayMs/60000),hours=Math.floor(minutes/60);
  const serviceChanges=[
    Math.abs(report.educationAfter-report.educationBefore)>=1?row('Education access',`${percent(report.educationBefore)} → ${percent(report.educationAfter)}`):'',
    Math.abs(report.healthcareAfter-report.healthcareBefore)>=1?row('Healthcare access',`${percent(report.healthcareBefore)} → ${percent(report.healthcareAfter)}`):'',
    Math.abs(report.wasteAfter-report.wasteBefore)>=.1?row('Waste backlog',`${report.wasteBefore.toFixed(1)} → ${report.wasteAfter.toFixed(1)} t`):'',
    Math.abs(report.qolAfter-report.qolBefore)>=.5?row('Quality of Life',`${report.qolBefore.toFixed(1)} → ${report.qolAfter.toFixed(1)}`):'',
    report.firesContained?row('Fire incidents contained',report.firesContained):'',
    Math.abs(report.rentAfter-report.rentBefore)>=100?row('Indicative household rent',`${compactMoney(report.rentBefore)} → ${compactMoney(report.rentAfter)}`):'',
    Math.abs(report.affordabilityAfter-report.affordabilityBefore)>=1?row('Housing affordability',`${percent(report.affordabilityBefore)} → ${percent(report.affordabilityAfter)}`):'',
    report.displacedResidents?row('Residents seeking replacement housing',report.displacedResidents):'',
  ].join('');
  return `<p>Away for ${hours}h ${minutes%60}m. ${(report.ticks/30).toFixed(1)} simulation months passed.</p><h3>Transit while away</h3><p>Daily boardings ${Math.round(report.transitBefore??0)} → ${Math.round(report.transitAfter??0)} · useful access ${Math.round(report.transitAccessBefore??0)}% → ${Math.round(report.transitAccessAfter??0)}% · jobs within 45 min ${Math.round(report.transitJobsBefore??0)} → ${Math.round(report.transitJobsAfter??0)}</p><dl>${row('Population',`${report.populationBefore.toLocaleString()} → ${report.populationAfter.toLocaleString()}`)}${row('Net residents',`${report.population>=0?'+':''}${report.population}`)}${row('Jobs',`${report.jobsBefore.toLocaleString()} → ${report.jobsAfter.toLocaleString()}`)}${row('Organic markets',`${report.marketsBefore} → ${report.marketsAfter}`)}${row('Buildings opened',report.buildingsOpened)}${row('Businesses opened',report.businessesOpened)}${row('Businesses closed',report.businessesClosed)}${row('Buildings upgraded',report.upgrades)}${row('Automatic tax revenue',compactMoney(report.taxRevenue))}${row('Treasury change',compactMoney(report.revenue))}${row('Grid reliability',`${Math.round(report.gridBefore)}% → ${Math.round(report.gridAfter)}%`)}${row('Water reliability',`${Math.round(report.waterBefore)}% → ${Math.round(report.waterAfter)}%`)}${row('Property flood incidents',report.floodProperties)}${row('Flooded tile incidents',report.floodIncidents)}${row('Estimated lost private output',compactMoney(report.economicLoss))}${row('Average commute',`${report.commuteBefore.toFixed(1)} → ${report.commuteAfter.toFixed(1)} min`)}${row('Congestion',`${Math.round(report.congestionBefore)}% → ${Math.round(report.congestionAfter)}%`)}${row('Active transport routes',`${report.routesBefore} → ${report.routesAfter}`)}${row('Safety incidents / serious',`${report.safetyIncidents} / ${report.seriousSafetyIncidents}`)}${row('Public safety',`${Math.round(report.safetyBefore)}% → ${Math.round(report.safetyAfter)}%`)}${row('Police response',`${report.policeResponseBefore.toFixed(1)} → ${report.policeResponseAfter.toFixed(1)} min`)}${serviceChanges}</dl>${report.events.length?`<h3>While you were away</h3><ul class="return-events">${report.events.map(escapeHtml).map(e=>`<li>${e}</li>`).join('')}</ul>`:''}<p class="hint">${report.awayMs>report.simulatedMs+5000?'Catch-up was limited to 24 real hours; longer absences are truncated.':'These changes have already happened. Continue planning from the current city state.'}</p>`;
}
