import type { City, Tile } from '../../shared/types/city';
import type { ServiceGroup } from '../../shared/types/public-services';
import { PUBLIC_SERVICES, SERVICE_GROUPS } from '../../shared/simulation/public-service-config';
import { compactMoney, escapeHtml } from './panels';
const num=(n:number)=>n.toLocaleString('en-NG',{maximumFractionDigits:1});
const pct=(n:number)=>`${Math.round(n)}%`;
const row=(k:string,v:string)=>`<div><dt>${k}</dt><dd>${v}</dd></div>`;
export const serviceLabels:Record<ServiceGroup,string>={police:'Police',education:'Education',healthcare:'Healthcare',fire:'Emergency',waste:'Waste',parks:'Parks'};

export function publicOverlayButtons(){return `<h3>Public services</h3><div class="overlay-buttons">${SERVICE_GROUPS.map(g=>`<button data-overlay="${g}">${serviceLabels[g]}</button>`).join('')}<button data-overlay="quality-of-life">Quality of Life</button></div><p class="hint">Green: good effective service. Amber: strained. Red: poor or none. Capacity, staffing and travel time all count.</p>`;}
export function publicBudgets(city:City){return SERVICE_GROUPS.map(g=>`<label class="budget-label">${serviceLabels[g]} funding <select data-public-budget="${g}">${[50,75,100,125,150].map(v=>`<option value="${v}" ${city.publicServices.funding[g]===v?'selected':''}>${v}%</option>`).join('')}</select></label>`).join('')+'<p class="hint">Funding above 100% gives diminishing capacity gains. Staffing, utilities and roads remain necessary. Deficits reduce delivered funding.</p>';}
export function publicSummary(city:City){const p=city.publicServices;return `<h3>Public services & Quality of Life</h3><dl>${SERVICE_GROUPS.map(g=>{const s=p.stats[g];return row(`${serviceLabels[g]} served`,`${pct(s.served/Math.max(1,s.demand)*100)} · ${num(s.served)} / ${num(s.demand)}`);}).join('')}${row('Waste generated / collected',`${num(p.waste.generated)} / ${num(p.waste.collected)} t/day`)}${row('Waste backlog',`${num(p.waste.backlog)} tonnes`)}${row('Public staff',`${num(p.employed)} / ${num(p.publicJobs)}`)}${row('Fire response',p.averageResponse?`${num(p.averageResponse)} min`:'No completed responses')}${row('Active fires',String(p.fires.filter(f=>f.resolvedAt===null).length))}${row('Quality of Life',`${num(p.qualityOfLife)} / 100`)}</dl><p class="hint">Quality of Life tracks structural conditions slowly. Satisfaction reflects current resident sentiment.</p><dl>${Object.entries(p.breakdown).map(([k,v])=>row(k,pct(v))).join('')}</dl>`;}
export function publicServicePanel(city:City,group:string){const g=group as ServiceGroup;if(!SERVICE_GROUPS.includes(g))return publicSummary(city);return `<p>Road travel time determines access. Coverage alone does not guarantee sufficient capacity. Public staff are hired from the same local workforce as private businesses.</p>${Object.entries(PUBLIC_SERVICES).filter(([,d])=>d.group===g).map(([kind,d])=>`<button class="tool" data-tool="${kind}"><span>⌂</span><div><b>${d.name}</b><small>${compactMoney(d.cost)} build · ${compactMoney(d.monthlyCost)}/month<br>${num(d.capacity)} ${d.group==="education"?"seats":d.group==="healthcare"?"visits/month":d.group==="waste"?"t/day":d.group==="parks"?"people":"population readiness"} · ${d.role}<br>${d.staff} staff · ${d.footprint}×${d.footprint} land · ${d.minutes} min access</small></div></button>`).join('')}<h3>${serviceLabels[g]} facilities</h3>${city.publicServices.facilities.filter(f=>f.type===g).map(f=>`<button class="tool" data-service-focus="${f.location}"><div><b>${escapeHtml(f.name)}</b><small>${f.status.replaceAll('-',' ')} · ${num(f.currentUsage)} demand / ${num(f.effectiveCapacity)} capacity</small></div></button>`).join('')}${publicBudgets(city)}`;}
export function publicInspector(city:City,t:Tile){const s=t.publicServices,f=city.publicServices.facilities.find(a=>a.id===t.publicFacility);let html=f?`<h3>${escapeHtml(f.name)}</h3><dl>${row('Status',f.status.replaceAll('-',' '))}${row('Demand / effective capacity',`${num(f.currentUsage)} / ${num(f.effectiveCapacity)}`)}${row('Base capacity',num(f.capacity))}${row('Actually served',num(f.served))}${row('Staff',`${f.employeesAvailable} / ${f.employeesRequired}`)}${row('Funding / condition',`${pct(f.fundingLevel)} / ${pct(f.maintenanceCondition)}`)}${row('Power / water reliability',`${pct(f.powerReliability)} / ${pct(f.waterReliability)}`)}${row('Service quality',pct(f.serviceQuality))}${row('Travel reach',`${f.coverageMinutes} min`)}${row('Average access score',pct(f.averageAccess))}${row('Monthly operating cost',compactMoney(f.monthlyOperatingCost))}${f.subtype==='landfill'?row('Waste stored',`${num(f.storedWaste)} t`):''}</dl><button data-service-active="${escapeHtml(f.id)}">${f.active?'Suspend':'Reopen'} facility</button>`:'';
  html+=`<h3>Local public services</h3><dl>${SERVICE_GROUPS.map(g=>row(serviceLabels[g],`${pct(s[g].quality)} quality · ${pct(s[g].served)} served · ${pct(s[g].access)} travel reach`)).join('')}${row('School-age population',num(s.educationDemand))}${row('Waste backlog',`${num(s.uncollectedWaste)} t`)}${row('Fire risk / damage',`${pct(s.fireRisk)} / ${pct(s.fireDamage)}`)}${row('Local Quality of Life',`${num(s.qualityOfLife)} / 100`)}</dl>`;return html;}
