import { emergencyIncidents } from '../../shared/simulation/emergency-coordination';
import type { City, Tile } from '../../shared/types/city';
import { escapeHtml } from './panels';
export const SAFETY_OVERLAYS=['public-safety','crime-pressure','police','night-safety','lighting','police-capacity','police-access','response-time'] as const;
const row=(k:string,v:string)=>`<div><dt>${escapeHtml(k)}</dt><dd>${v}</dd></div>`;
const pct=(v:number)=>`${Math.round(v)}%`;
export function safetySummary(city: City) {
  const m=city.safety.metrics;
  return `<h3>Public safety</h3><dl>${row('Public safety',pct(m.publicSafety))}${row('Structural crime pressure',pct(m.crimePressure))}${row('Night safety',pct(m.nightSafety))}${row('Community prevention',pct(m.communitySafety))}${row('Effective police access',pct(m.policeAccess))}${row('Police readiness / demand',`${Math.round(m.capacity).toLocaleString()} / ${Math.round(m.demand).toLocaleString()}`)}${row('Estimated response',m.policeAccess>0?`${m.responseMinutes.toFixed(1)} min`:'No reachable staffed response')}${row('Incidents / last 30 days',String(m.incidents30Days))}${row('Active incidents',String(m.activeIncidents))}${row('Powered street lighting',pct(m.lighting))}</dl><p class="hint">Prevention reduces incident pressure. Response limits consequences. Employment, stable housing, active streets and services matter alongside policing. Income or informal tenure alone never cause crime.</p><div class="overlay-buttons">${SAFETY_OVERLAYS.map(o=>`<button data-overlay="${o}">${o.replaceAll('-',' ')}</button>`).join('')}</div><button data-service="police">Build / fund police services</button><h3>Emergency coordination</h3><p>${emergencyIncidents(city).filter(i=>i.resolvedAt===null).length} active fire/police incidents. Healthcare remains a road-accessible staffed service; no new medical incident simulation.</p><h3>Recent incidents</h3>${city.safety.incidents.slice(-12).reverse().map(i=>`<button class="tool" data-safety-focus="${i.location}"><div><b>${escapeHtml(i.type.replace('-',' '))} · ${i.severity}</b><small>Day ${i.startTime} · ${i.status} · ${i.responseTime.toFixed(1)} min</small></div></button>`).join('')||'<p>No recent incidents.</p>'}`;
}
export function safetyInspector(city: City, t: Tile) {
  const id=t.y*city.size+t.x,a=city.safety.local[id],f=city.safety.facilities.find(f=>f.facilityId===t.publicFacility);
  let html=`<h3>Local safety & prevention</h3><dl>${row('Public safety',pct(a.publicSafety))}${row('Crime pressure',pct(a.crimePressure))}${row('Night / commercial safety',`${pct(a.nightSafety)} / ${pct(a.commercialSafety)}`)}${row('Community prevention',pct(a.communitySafety))}${row('Lighting reliability',pct(a.lighting))}${row('Effective patrol / access',`${pct(a.patrol)} / ${pct(a.policeAccess)}`)}${row('Estimated response',a.policeAccess>0?`${a.responseMinutes.toFixed(1)} min`:'No reachable staffed response')}${row('Recent incident memory',a.recentIncidents.toFixed(1))}${f?row('Active responses / available slots',`${f.activeIncidents} / ${f.responseSlots.toFixed(1)}`):''}</dl><p class="hint">Pressure contributors: economic stress ${Math.round(a.model.economicStress)}, employment stress ${Math.round(a.model.employmentStress)}, housing instability ${Math.round(a.model.housingStress)}, service gaps ${Math.round(a.model.serviceStress)}. Stabilizers: community activity ${Math.round(a.model.community)}, visibility ${Math.round(a.model.visibility)}, patrol ${Math.round(a.model.patrol)}.</p>`;
  for(const i of city.safety.incidents.filter(i=>i.location===id).slice(-3).reverse())html+=`<h3>${escapeHtml(i.type.replace('-',' '))} incident</h3><dl>${row('Severity',i.severity)}${row('Reported',`Day ${i.startTime}`)}${row('Response status',i.status)}${row('Dispatch / travel',`${i.responseTime.toFixed(1)} min`)}${row('Responding facility',escapeHtml(city.publicServices.facilities.find(f=>f.id===i.respondingUnit)?.name??'No reachable response available'))}${row('Outcome',escapeHtml(i.resolution??'Response and recovery in progress'))}</dl>`;
  return html;
}
