import type { City, Tile } from '../../shared/types/city';
import { accessBand, TRANSIT, TRANSIT_FACILITIES, TRANSIT_OVERLAYS, TRANSIT_PERIODS, TRANSIT_VEHICLES } from '../../shared/simulation/transit-config';
import { transitPeriodLoads } from '../../shared/simulation/transit';
import { districtMobility, personCapacity, transitReport } from '../../shared/simulation/transit-metrics';
import { compactMoney, escapeHtml } from './panels';
const row = (label: string, value: string | number) => `<div><dt>${label}</dt><dd>${value}</dd></div>`;
const pct = (v: number) => `${Math.round(v)}%`;
// Aggregate estimates: round to a sensible precision rather than implying exact counts.
const about = (v: number) => (v >= 1000 ? Math.round(v / 100) * 100 : v >= 100 ? Math.round(v / 10) * 10 : Math.round(v)).toLocaleString();
const routeName = (city: City, id: string) => city.transit.routes.find(r => r.id === id)?.name ?? id;
export function transitSummary(city: City) {
  const t = city.transit, s = t.stats, f = t.finance;
  return `<h3>Metropolitan network</h3><p>${escapeHtml(s.profile)}</p><dl>${row('Formal daily boardings', Math.round(s.ridership).toLocaleString())}${row('Useful transit access', `${pct(s.access)} · ${accessBand(s.access)}`)}${row('Jobs reached within 45 minutes', Math.round(s.jobs45).toLocaleString())}${row('Average wait', `${s.wait.toFixed(1)} min`)}${row('Reliability', pct(s.reliability))}${row('Crowding in the busiest period', pct(s.crowding * 100))}${row('Peak people throughput / hour', about(s.throughput))}${row('Fleet / depot slots', `${s.assignedFleet} / ${s.depotCapacity}`)}${row('Bus operations / month',compactMoney(f.bus))}${row('BRT operations / month',compactMoney(f.brt))}${row('Stations / corridors / month',compactMoney(f.stations))}${row('Terminals / integration / month',compactMoney(f.terminals))}${row('Depots / month',compactMoney(f.depots))}${row('Monthly fares', compactMoney(f.fares))}${row('Monthly operating subsidy', compactMoney(f.subsidy))}${row('Farebox recovery', pct(f.recovery))}</dl><p class="hint">Boardings include transfers; mode shares count trips once. Accessibility measures useful service, not simply proximity to a stop.</p><div class="transport-tabs">${TRANSIT_OVERLAYS.map(o => `<button data-overlay="${o}">${o.replaceAll('transit-', '').replaceAll('-', ' ')}</button>`).join('')}</div>`;
}
export function transitPlanningPanel(city: City, tab: string, selected: string | null) {
  const t = city.transit;
  const nav = `<div class="transport-tabs">${['overview', 'roads', 'informal', 'bus', 'brt', 'network'].map(n => `<button data-transport-tab="${n}" aria-pressed="${tab === n}">${n}</button>`).join('')}</div>`;
  if (tab === 'network') return nav + transitSummary(city) + `<h3>Operations & integration</h3><label class="budget-label">Fare support<select data-transit-subsidy>${[0, 25, 50, 75].map(n => `<option value="${n}" ${t.subsidyRate === n ? 'selected' : ''}>${n}% fare reduction</option>`).join('')}</select></label><p>Fare support reduces passenger costs and fare revenue. The city pays the remaining operating balance.</p><label class="budget-label">Informal network<select data-transit-integration>${['neutral', 'integrate', 'support'].map(n => `<option ${t.integration === n ? 'selected' : ''}>${n}</option>`).join('')}</select></label><p class="hint">Integration improves feeder boarding at formal hubs; support additionally helps recognized operators. Danfo/Keke remain privately operated.</p><h3>District mobility</h3>${districtMobility(city).map(d => `<p><b>${escapeHtml(d.name)}</b> · transit access ${accessBand(d.access).toLowerCase()} (${pct(d.access)}) · ${about(d.jobs45)} jobs within ${TRANSIT.jobMinutes} minutes · commute ${d.trips ? `${Math.round(d.commute)} min, ${pct(d.within45)} within ${TRANSIT.jobMinutes}` : 'no trips yet'} · shared transport ${pct(d.sharedShare)} (bus ${pct(d.trips ? d.modes.bus / d.trips * 100 : 0)}, BRT ${pct(d.trips ? d.modes.brt / d.trips * 100 : 0)}, Danfo/Keke ${pct(d.trips ? (d.modes.danfo + d.modes.keke) / d.trips * 100 : 0)}) · car ${pct(d.trips ? d.modes.car / d.trips * 100 : 0)}</p>`).join('') || '<p>Create districts in Governance to compare access, commutes and mode share.</p>'}<h3>Facilities</h3>${Object.entries(TRANSIT_FACILITIES).map(([kind, def]) => `<button class="tool" data-tool="${kind}"><div><b>${def.name}</b><small>${compactMoney(def.cost)} construction · ${compactMoney(def.monthly)}/month</small></div></button>`).join('')}`;
  const mode = tab === 'brt' ? 'brt' : 'bus';
  const route = t.routes.find(r => r.id === selected);
  const detail = route ? `<section class="route-detail"><h3>${escapeHtml(route.name)} · ${route.mode.toUpperCase()}</h3><p>${route.status === 'no-depot' ? 'No reachable depot fleet capacity. Build a depot or reduce assigned fleets.' : route.status === 'disrupted' ? 'A stop or road path is unavailable. The route reroutes where possible; restore access or edit its stops.' : escapeHtml(route.status)}</p><dl>${row('Stops', route.stops.length)}${row('Length', `${route.length.toFixed(2)} km`)}${row('Vehicles assigned / available', `${route.vehicles} / ${route.availableVehicles}`)}${row('Headway', `${route.headway.toFixed(1)} min`)}${row('Daily demand / boardings', `${about(route.demand)} / ${about(route.ridership)}`)}${row('Passenger capacity / day', about(route.capacity))}${row('Crowding in the busiest period', pct(route.crowding * 100))}${periods(city, route.id)}${row('Average wait', `${route.wait.toFixed(1)} min`)}${row('End-to-end journey', `${route.minutes.toFixed(1)} min`)}${row('Reliability', pct(route.reliability))}${row('Operating cost / month', compactMoney(route.operatingCost))}${row('Fare revenue / month', compactMoney(route.revenue))}${row('Operating subsidy / month', compactMoney(route.subsidy))}</dl><label class="budget-label">Name<input data-transit-name="${route.id}" maxlength="80" value="${escapeHtml(route.name)}" /></label><label class="budget-label">Fare ₦<input type="number" data-transit-fare="${route.id}" min="0" max="3000" value="${route.fare}" /></label><div class="settings-actions"><button data-transit-fleet="1">Add vehicle · ${compactMoney(TRANSIT_VEHICLES[route.mode].cost)}</button><button data-transit-fleet="-1">Withdraw vehicle</button><button data-transit-suspend>${route.suspended ? 'Resume' : 'Suspend'}</button><button data-transit-focus="${route.id}">Find route ↗</button><button data-transit-edit>Edit ordered stops</button><button data-transit-remove>Retire service</button></div><h3>Ordered stops</h3>${route.stops.map(id => { const stop = t.stops.find(s => s.id === id); return stop ? `<button data-transit-stop="${id}">${escapeHtml(stop.name)} ↗</button>` : ''; }).join('')}</section>` : '';
  return nav + `<p>${mode === 'brt' ? 'Build dedicated lanes on avenues/major roads and BRT stations. General vehicle capacity falls; transit bypasses much congestion.' : 'Place stops beside trip origins and destinations, add a connected depot, then select stops in order. Empty corridors produce no passengers.'}</p>${mode === 'brt' ? '<button data-action="brt-corridor">Plan dedicated corridor</button><button data-tool="brt-station">Place BRT station · ₦18M</button>' : '<button data-tool="bus-stop">Place bus stop · ₦300K</button>'}<button class="primary" data-action="transit-plan" data-transit-mode="${mode}">Create ${mode.toUpperCase()} route</button><button data-tool="bus-depot">Build depot · ₦60M / 60 vehicles</button>` + detail + t.routes.filter(r => r.mode === mode).map(r => `<button class="route-card" data-transit-route="${r.id}"><small>${r.mode === 'brt' ? 'BRT' : r.legacy ? 'Bus · existing service' : 'Bus'} · ${r.status}${r.crowding > 1 ? ' · crowded' : ''}</small><b>${escapeHtml(r.name)}</b><span>${about(r.ridership)} boardings/day · ${r.vehicles} vehicles · ${r.headway.toFixed(1)} min headway</span></button>`).join('');
}
function periods(city: City, id: string) {
  const load = transitPeriodLoads(city, id); if (!load) return '';
  return row('Boardings by period', TRANSIT_PERIODS.map((p, i) => `${p.name.toLowerCase()} ${about(load.riders[i])}`).join(' · '));
}
export function transitInspector(city: City, tile: Tile) {
  const id = tile.y * city.size + tile.x, stop = city.transit.stops.find(s => s.tileId === id), l = city.transit.local[id];
  let html = `<h3>Transit access</h3><dl>${row('Useful access', `${pct(l.access)} · ${accessBand(l.access)}`)}${row('Jobs within 45 minutes', Math.round(l.jobs45))}${row('First / last mile', `${pct(l.firstMile)} / ${pct(l.lastMile)}`)}${row('Station-area development support', l.tod.toFixed(1))}</dl>`;
  if (stop) html += `<h3>${escapeHtml(stop.name)}</h3><dl>${row('Facility', TRANSIT_FACILITIES[stop.kind].name)}${row('Routes served', stop.routes.length ? stop.routes.map(id => escapeHtml(routeName(city, id))).join(', ') : 'none')}${row('Boardings / transfers', `${about(stop.boardings)} / ${about(stop.transfers)}`)}${row('Demand', about(stop.demand))}${row('Passenger handling capacity', stop.capacity)}${row('Crowding in the busiest period', pct(stop.crowding * 100))}${row('Walking access', pct(stop.accessibility))}${row('Night safety / lighting', `${pct(stop.nightSafety)} / ${pct(stop.lighting)}`)}${row('Police accessibility', pct(city.safety.local[id].policeAccess))}</dl>${stop.routes.map(r => `<button data-transit-route="${r}">Inspect ${escapeHtml(routeName(city, r))} ↗</button>`).join('')}`;
  if (tile.road) { const people = personCapacity(city, id); html += `<dl>${row('People moved / peak hour', about(people.moved))}${row('People capacity / hour', `${about(people.total)} (general lanes ${about(people.general)}, scheduled transit ${about(people.transit)})`)}</dl>`; }
  if (tile.road) html += `<p>${city.transit.corridors.includes(id) ? 'Dedicated BRT space · general vehicle capacity reduced.' : ''}${city.transit.works[id] > city.tick ? ` Works until day ${city.transit.works[id]}.` : ''}</p><div class="settings-actions">${['signal', 'high-capacity', 'roundabout'].map(k => `<button data-junction="${k}">${k.replaceAll('-', ' ')} junction</button>`).join('')}</div>`;
  return html;
}
/** Developer diagnostics: trip demand, transit demand, boardings, transfers, mode share and capacity. */
export function transitReportHtml(city: City) {
  const r = transitReport(city), trips = Math.max(1, Object.values(r.modes).reduce((a, b) => a + b, 0));
  const list = (items: string[]) => items.length ? `<ul>${items.map(i => `<li>${i}</li>`).join('')}</ul>` : '<p>None yet.</p>';
  return `<section class="transit-report"><h3>Transit report</h3><dl>${row('Daily trips / OD flows', `${about(r.trips.daily)} / ${r.trips.flows}`)}${row('Planned journeys / passengers', `${r.journeys.count} / ${about(r.journeys.passengers)}`)}${row('Journeys with a transfer', pct(r.journeys.transferShare))}${row('Average planned journey', `${Math.round(r.journeys.minutes)} min`)}${row('Useful access / jobs within 45 min', `${pct(r.access)} / ${about(r.jobs45)}`)}${row('Ridership-weighted reliability', pct(r.reliability))}${row('People per peak hour', about(r.throughput))}${row('Graph builds / queries / cached origins', `${r.cache.builds} / ${r.cache.queries} / ${r.cache.sources}`)}</dl>`
    + `<h4>Mode share</h4><p>${Object.entries(r.modes).map(([mode, n]) => `${mode} ${pct(n / trips * 100)}`).join(' · ')}</p>`
    + `<h4>Largest trip flows</h4>${list(r.trips.top.map(f => `${escapeHtml(f.from)} → ${escapeHtml(f.to)} · ${f.purpose} · ${about(f.trips)} trips · ${Math.round(f.minutes)} min`))}`
    + `<h4>Routes</h4>${list(r.routes.map(x => `${escapeHtml(x.name)} (${x.mode}, ${x.status}) · ${about(x.ridership)} of ${about(x.demand)} wanted · capacity ${about(x.capacity)} · crowding ${pct(x.crowding * 100)} · reliability ${pct(x.reliability)} · every ${x.headway.toFixed(1)} min${x.periods ? ` · ${r.periods.map((p, i) => `${p.toLowerCase()} ${about(x.periods![i])}`).join(', ')}` : ''}`))}`
    + `<h4>Busiest stops</h4>${list(r.stops.map(x => `${escapeHtml(x.name)} (${x.kind}) · ${about(x.boardings)} boardings · ${about(x.transfers)} transfers · ${pct(x.crowding * 100)} load`))}`
    + `<h4>Transfer flows</h4>${list(r.transfers.map(x => `${escapeHtml(x.from)} → ${escapeHtml(x.to)} at (${x.tileId % city.size}, ${Math.floor(x.tileId / city.size)}) · ${about(x.passengers)}`))}</section>`;
}
