import type { City, Tile } from '../../shared/types/city';
import { TRANSIT_FACILITIES, TRANSIT_OVERLAYS, TRANSIT_VEHICLES } from '../../shared/simulation/transit-config';
import { compactMoney, escapeHtml } from './panels';
const row = (label: string, value: string | number) => `<div><dt>${label}</dt><dd>${value}</dd></div>`;
const pct = (v: number) => `${Math.round(v)}%`;
export function transitSummary(city: City) {
  const t = city.transit, s = t.stats, f = t.finance;
  return `<h3>Metropolitan network</h3><p>${escapeHtml(s.profile)}</p><dl>${row('Formal daily boardings', Math.round(s.ridership).toLocaleString())}${row('Useful transit access', pct(s.access))}${row('Jobs reached within 45 minutes', Math.round(s.jobs45).toLocaleString())}${row('Average wait', `${s.wait.toFixed(1)} min`)}${row('Reliability', pct(s.reliability))}${row('Peak people throughput / hour', Math.round(s.throughput).toLocaleString())}${row('Fleet / depot slots', `${s.assignedFleet} / ${s.depotCapacity}`)}${row('Bus operations / month',compactMoney(f.bus))}${row('BRT operations / month',compactMoney(f.brt))}${row('Stations / corridors / month',compactMoney(f.stations))}${row('Terminals / integration / month',compactMoney(f.terminals))}${row('Depots / month',compactMoney(f.depots))}${row('Monthly fares', compactMoney(f.fares))}${row('Monthly operating subsidy', compactMoney(f.subsidy))}${row('Farebox recovery', pct(f.recovery))}</dl><p class="hint">Boardings include transfers; mode shares count trips once. Accessibility measures useful service, not simply proximity to a stop.</p><div class="transport-tabs">${TRANSIT_OVERLAYS.map(o => `<button data-overlay="${o}">${o.replaceAll('transit-', '').replaceAll('-', ' ')}</button>`).join('')}</div>`;
}
export function transitPlanningPanel(city: City, tab: string, selected: string | null) {
  const t = city.transit;
  const nav = `<div class="transport-tabs">${['overview', 'roads', 'informal', 'bus', 'brt', 'network'].map(n => `<button data-transport-tab="${n}" aria-pressed="${tab === n}">${n}</button>`).join('')}</div>`;
  if (tab === 'network') return nav + transitSummary(city) + `<h3>Operations & integration</h3><label class="budget-label">Fare support<select data-transit-subsidy>${[0, 25, 50, 75].map(n => `<option value="${n}" ${t.subsidyRate === n ? 'selected' : ''}>${n}% fare reduction</option>`).join('')}</select></label><p>Fare support reduces passenger costs and fare revenue. The city pays the remaining operating balance.</p><label class="budget-label">Informal network<select data-transit-integration>${['neutral', 'integrate', 'support'].map(n => `<option ${t.integration === n ? 'selected' : ''}>${n}</option>`).join('')}</select></label><p class="hint">Integration improves feeder boarding at formal hubs; support additionally helps recognized operators. Danfo/Keke remain privately operated.</p><h3>District access</h3>${city.governance.districts.map(d => `<p><b>${escapeHtml(d.name)}</b> · ${pct(t.districts[d.id]?.access ?? 0)} useful transit access · ${Math.round(t.districts[d.id]?.jobs45 ?? 0)} jobs within 45 minutes</p>`).join('') || '<p>Create districts in Governance to compare access.</p>'}<h3>Facilities</h3>${Object.entries(TRANSIT_FACILITIES).map(([kind, def]) => `<button class="tool" data-tool="${kind}"><div><b>${def.name}</b><small>${compactMoney(def.cost)} construction · ${compactMoney(def.monthly)}/month</small></div></button>`).join('')}`;
  const mode = tab === 'brt' ? 'brt' : 'bus';
  const route = t.routes.find(r => r.id === selected);
  const detail = route ? `<section class="route-detail"><h3>${escapeHtml(route.name)} · ${route.mode.toUpperCase()}</h3><p>${route.status === 'no-depot' ? 'No reachable depot fleet capacity. Build a depot or reduce assigned fleets.' : route.status === 'disrupted' ? 'A stop or road path is unavailable. The route reroutes where possible; restore access or edit its stops.' : escapeHtml(route.status)}</p><dl>${row('Stops', route.stops.length)}${row('Length', `${route.length.toFixed(2)} km`)}${row('Vehicles assigned / available', `${route.vehicles} / ${route.availableVehicles}`)}${row('Headway', `${route.headway.toFixed(1)} min`)}${row('Daily demand / boardings', `${Math.round(route.demand)} / ${Math.round(route.ridership)}`)}${row('Passenger capacity / day', Math.round(route.capacity))}${row('Crowding', `${Math.round(route.crowding * 100)}%`)}${row('Average wait', `${route.wait.toFixed(1)} min`)}${row('End-to-end journey', `${route.minutes.toFixed(1)} min`)}${row('Reliability', pct(route.reliability))}${row('Operating cost / month', compactMoney(route.operatingCost))}${row('Fare revenue / month', compactMoney(route.revenue))}${row('Operating subsidy / month', compactMoney(route.subsidy))}</dl><label class="budget-label">Name<input data-transit-name="${route.id}" maxlength="80" value="${escapeHtml(route.name)}" /></label><label class="budget-label">Fare ₦<input type="number" data-transit-fare="${route.id}" min="0" max="3000" value="${route.fare}" /></label><div class="settings-actions"><button data-transit-fleet="1">Add vehicle · ${compactMoney(TRANSIT_VEHICLES[route.mode].cost)}</button><button data-transit-fleet="-1">Withdraw vehicle</button><button data-transit-suspend>${route.suspended ? 'Resume' : 'Suspend'}</button><button data-transit-focus="${route.id}">Find route ↗</button><button data-transit-edit>Edit ordered stops</button><button data-transit-remove>Retire service</button></div><h3>Ordered stops</h3>${route.stops.map(id => { const stop = t.stops.find(s => s.id === id); return stop ? `<button data-transit-stop="${id}">${escapeHtml(stop.name)} ↗</button>` : ''; }).join('')}</section>` : '';
  return nav + `<p>${mode === 'brt' ? 'Build dedicated lanes on avenues/major roads and BRT stations. General vehicle capacity falls; transit bypasses much congestion.' : 'Place stops beside trip origins and destinations, add a connected depot, then select stops in order. Empty corridors produce no passengers.'}</p>${mode === 'brt' ? '<button data-action="brt-corridor">Plan dedicated corridor</button><button data-tool="brt-station">Place BRT station · ₦18M</button>' : '<button data-tool="bus-stop">Place bus stop · ₦300K</button>'}<button class="primary" data-action="transit-plan" data-transit-mode="${mode}">Create ${mode.toUpperCase()} route</button><button data-tool="bus-depot">Build depot · ₦60M / 60 vehicles</button>` + detail + t.routes.filter(r => r.mode === mode).map(r => `<button class="route-card" data-transit-route="${r.id}"><small>Line ${escapeHtml(r.id)} · ${r.status}</small><b>${escapeHtml(r.name)}</b><span>${Math.round(r.ridership)} boardings/day · ${r.vehicles} vehicles · ${r.headway.toFixed(1)} min headway</span></button>`).join('');
}
export function transitInspector(city: City, tile: Tile) {
  const id = tile.y * city.size + tile.x, stop = city.transit.stops.find(s => s.tileId === id), l = city.transit.local[id];
  let html = `<h3>Transit access</h3><dl>${row('Useful access', pct(l.access))}${row('Jobs within 45 minutes', Math.round(l.jobs45))}${row('First / last mile', `${pct(l.firstMile)} / ${pct(l.lastMile)}`)}${row('Station-area development support', l.tod.toFixed(1))}</dl>`;
  if (stop) html += `<h3>${escapeHtml(stop.name)}</h3><dl>${row('Facility', TRANSIT_FACILITIES[stop.kind].name)}${row('Boardings / transfers', `${Math.round(stop.boardings)} / ${Math.round(stop.transfers)}`)}${row('Demand', Math.round(stop.demand))}${row('Passenger handling capacity', stop.capacity)}${row('Crowding', `${Math.round(stop.crowding * 100)}%`)}${row('Walking access', pct(stop.accessibility))}${row('Night safety / lighting', `${pct(stop.nightSafety)} / ${pct(stop.lighting)}`)}${row('Police accessibility', pct(city.safety.local[id].policeAccess))}</dl>${stop.routes.map(r => `<button data-transit-route="${r}">Inspect line ${escapeHtml(r)} ↗</button>`).join('')}`;
  if (tile.road) html += `<p>${city.transit.corridors.includes(id) ? 'Dedicated BRT space · general vehicle capacity reduced.' : ''}${city.transit.works[id] > city.tick ? ` Works until day ${city.transit.works[id]}.` : ''}</p><div class="settings-actions">${['signal', 'high-capacity', 'roundabout'].map(k => `<button data-junction="${k}">${k.replaceAll('-', ' ')} junction</button>`).join('')}</div>`;
  return html;
}
