import Phaser from 'phaser';
import { CityScene } from './CityScene';
import { gameConfig } from './game-config';
import { publicServiceFixture } from '../../shared/simulation/public-service-fixtures';
import { cityActivity } from '../../shared/simulation/activity';
import { updatePublicServices, triggerFire } from '../../shared/simulation/public-services';
import { serviceCacheDiagnostics } from '../../shared/simulation/public-service-access';
import { decodeCity } from '../../shared/simulation/save-format';
import { advance, catchUp, TICK_MS } from '../../shared/simulation/engine';
import type { GraphicsQuality } from './visual-style';
import type { Overlay } from '../../shared/types/city';
if(!import.meta.env.DEV)throw new Error('Service QA is development-only.');
let city=publicServiceFixture(1000),hour=8;
document.body.style.cssText='margin:0;background:#b5b49f;font:12px system-ui;color:#243d34';
document.querySelector('#app')!.innerHTML=`<div id="game" style="position:fixed;inset:0"></div><aside id="qa" style="position:fixed;top:8px;left:8px;right:8px;background:#f5f0e2ed;padding:10px;z-index:10;max-height:25vh;overflow:auto"><b>Public services QA · isolated aggregate city</b><div style="display:flex;gap:6px;flex-wrap:wrap;margin:8px 0"><select id="population">${[1000,10000,100000,500000].map(n=>`<option>${n}</option>`).join('')}</select><select id="quality"><option>high</option><option>medium</option><option>low</option></select><select id="overlay">${['none','education','healthcare','fire','waste','parks','quality-of-life'].map(o=>`<option>${o}</option>`).join('')}</select>${['home','school','hospital','park','fire','waste','utilities','restore','month','reload','offline','photo'].map(a=>`<button id="${a}">${a}</button>`).join('')}</div><output id="metrics"></output><p id="result"></p></aside>`;
const quality:GraphicsQuality=innerWidth<600?'medium':'high';
const scene=new CityScene(()=>city,()=> 'inspect',()=>{},()=>{});scene.setGraphicsQuality(quality);new Phaser.Game(gameConfig(scene,quality));
(document.querySelector('#quality') as HTMLSelectElement).value=quality;
const redraw=()=>{scene.setActivity(cityActivity(city,hour));scene.redraw();};
const result=(s:string)=>{document.querySelector('#result')!.textContent=s;};
const focus=(type:string)=>{const f=city.publicServices.facilities.find(f=>f.type===type);if(f){scene.zoomTo(4);const t=city.tiles[f.location];setTimeout(()=>scene.focusTile(t.x,t.y),650);}};
document.querySelector<HTMLSelectElement>('#population')!.onchange=e=>{city=publicServiceFixture(Number((e.target as HTMLSelectElement).value) as 1000|10000|100000|500000);redraw();scene.home();result(`${city.population} residents from actual housing occupancy.`);};
document.querySelector<HTMLSelectElement>('#quality')!.onchange=e=>scene.setGraphicsQuality((e.target as HTMLSelectElement).value as GraphicsQuality);
document.querySelector<HTMLSelectElement>('#overlay')!.onchange=e=>scene.setOverlay((e.target as HTMLSelectElement).value as Overlay);
document.querySelector<HTMLButtonElement>('#home')!.onclick=()=>scene.home();
document.querySelector<HTMLButtonElement>('#school')!.onclick=()=>focus('education');
document.querySelector<HTMLButtonElement>('#hospital')!.onclick=()=>focus('healthcare');
document.querySelector<HTMLButtonElement>('#park')!.onclick=()=>focus('parks');
document.querySelector<HTMLButtonElement>('#fire')!.onclick=()=>{const id=city.tiles.findIndex(t=>t.building?.type==='residential');triggerFire(city,id);redraw();const t=city.tiles[id];scene.focusTile(t.x,t.y);result('Actual fire incident and cached station response.');};
document.querySelector<HTMLButtonElement>('#waste')!.onclick=()=>{for(const t of city.tiles)if(t.building)t.publicServices.uncollectedWaste+=t.publicServices.wasteGenerated*30;updatePublicServices(city,false);redraw();result('Actual backlog added to occupied parcels.');};
document.querySelector<HTMLButtonElement>('#utilities')!.onclick=()=>{for(const t of city.tiles){t.services.powerReliability=0;t.services.waterReliability=0;}updatePublicServices(city,false);redraw();result('Utility failure lowers facility quality/capacity.');};
document.querySelector<HTMLButtonElement>('#restore')!.onclick=()=>{for(const t of city.tiles){t.services.powerReliability=90;t.services.waterReliability=90;}updatePublicServices(city,false);redraw();result('Public utility supply restored for benchmark.');};
document.querySelector<HTMLButtonElement>('#month')!.onclick=()=>{advance(city,30);redraw();result('One simulation month: hiring, service operation, waste, repairs and QoL.');};
document.querySelector<HTMLButtonElement>('#reload')!.onclick=()=>{const before=JSON.stringify(city);city=decodeCity(JSON.parse(before));result(JSON.stringify(city)===before?'Save/reload: every field preserved.':'Save/reload changed state.');redraw();};
document.querySelector<HTMLButtonElement>('#offline')!.onclick=()=>{const active=decodeCity(JSON.parse(JSON.stringify(city))),away=decodeCity(JSON.parse(JSON.stringify(city)));advance(active,30);const now=city.lastSimulatedTimestamp+30*TICK_MS;active.lastSimulatedTimestamp=now;const report=catchUp(away,now);city=away;redraw();result(`Offline replay ${JSON.stringify(active)===JSON.stringify(away)?'identical':'DIFFERENT'} · QoL ${report.qolBefore.toFixed(1)} → ${report.qolAfter.toFixed(1)} · waste ${report.wasteAfter.toFixed(1)} t.`);};
document.querySelector<HTMLButtonElement>('#photo')!.onclick=()=>document.querySelector<HTMLElement>('#qa')!.hidden=true;
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector<HTMLElement>('#qa')!.hidden=false;});
Object.assign(window,{publicQA:{snapshot:()=>({ready:scene.sys.isActive(),population:city.population,services:city.publicServices,cache:serviceCacheDiagnostics(city),graphics:scene.graphicsSummary(),vehicles:scene.representativeVehicleCount,pedestrians:scene.representativePedestrianCount,activity:cityActivity(city,hour)})}});
setInterval(()=>{redraw();document.querySelector('#metrics')!.textContent=`${city.population.toLocaleString()} residents · QoL ${city.publicServices.qualityOfLife.toFixed(1)} · ${JSON.stringify(serviceCacheDiagnostics(city))} · ${scene.graphicsSummary()}`;},500);
