"""Compile Blender renders into grouped, padded LOD atlases and a typed catalog."""
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/'art/model/masters'
OUT=ROOT/'public/assets/model'
DOC=ROOT/'docs/architectural-model'
TIERS=(2,6,9,12)


def power2(n):
  return 2**math.ceil(math.log2(max(64,n)))


def build():
  OUT.mkdir(parents=True,exist_ok=True);DOC.mkdir(parents=True,exist_ok=True)
  assets=[];pictures={}
  for path in sorted(SRC.glob('*.json')):
    meta=json.loads(path.read_text(encoding='utf8'))
    if meta['type']=='demonstration':continue
    picture=Image.open(path.with_suffix('.png')).convert('RGBA')
    bounds=picture.getbbox()
    if not bounds:raise ValueError('Empty render '+meta['id'])
    original_size=list(picture.size)
    picture=picture.crop(bounds)
    scale=meta['sourceScale']
    origin=meta.pop('originPixels')
    anchor=[(origin[0]-bounds[0])/picture.width,
      (origin[1]-bounds[1]-meta.pop('tileTopOffset')*scale)/picture.height]
    asset=dict(meta,anchor=anchor,worldWidth=picture.width/scale,
      visualHeight=max(0,anchor[1]*picture.height/scale),masterSize=original_size)
    if asset['type']=='commercial':asset['floorHeightMetres']=3.8 if asset['level']>=3 else 3.6
    if asset['type']=='industrial':asset['floorHeightMetres']=5.2
    if asset['type'] in ['residential','commercial','industrial']:
      # Ground sockets projected from (-8.5,6), (8.5,-6.7), (8,6.5) metres.
      asset['sockets']={'generator':{'x':-17.4,'y':10.5},'tank':{'x':18.24,'y':13.08},'pump':{'x':1.8,'y':20.7}}
    assets.append(asset);pictures[asset['id']]=picture
  sheets={};locations={}
  for tier in TIERS:
    groups={}
    for a in assets:
      group=a['id'].split('-')[1] if a['type']=='road' else 'architecture'
      p=pictures[a['id']]
      size=(max(1,round(p.width/a['sourceScale']*tier)),max(1,round(p.height/a['sourceScale']*tier)))
      if size[0]>p.width or size[1]>p.height:raise ValueError('Upscaled master '+a['id'])
      groups.setdefault(group,[]).append((a,p.resize(size,Image.Resampling.LANCZOS)))
    sheets[tier]=[];locations[tier]={}
    for group,items in groups.items():
      size=512 if tier==2 else 2048
      if any(max(p.size)+4>size for _,p in items):size=2048
      pages=[]
      for a,p in sorted(items,key=lambda pair:pair[1].height,reverse=True):
        w,h=p.size;page=None
        for candidate in pages:
          x,y,row=candidate['x'],candidate['y'],candidate['row']
          if x+w+4>size:x,y,row=0,y+row,0
          if y+h+4<=size:
            page=candidate;page.update(x=x,y=y,row=row);break
        if page is None:
          page={'image':Image.new('RGBA',(size,size)),'x':0,'y':0,'row':0,'frames':{},'right':0,'bottom':0}
          pages.append(page)
        x,y=page['x']+2,page['y']+2
        page['image'].paste(p,(x,y))
        # Extruded border protects linear filtering at atlas frame edges.
        page['image'].paste(p.crop((0,0,1,h)).resize((2,h)),(x-2,y))
        page['image'].paste(p.crop((w-1,0,w,h)).resize((2,h)),(x+w,y))
        page['image'].paste(p.crop((0,0,w,1)).resize((w,2)),(x,y-2))
        page['image'].paste(p.crop((0,h-1,w,h)).resize((w,2)),(x,y+h))
        frame={'frame':{'x':x,'y':y,'w':w,'h':h},'rotated':False,'trimmed':False,
          'spriteSourceSize':{'x':0,'y':0,'w':w,'h':h},'sourceSize':{'w':w,'h':h}}
        page['frames']['model-'+a['id']]=frame
        page['x']+=w+4;page['row']=max(page['row'],h+4)
        page['right']=max(page['right'],x+w+2);page['bottom']=max(page['bottom'],y+h+2)
      for n,page in enumerate(pages):
        key=f'model-{group}-{tier}-{n}'
        width,height=power2(page['right']),power2(page['bottom'])
        page['image'].crop((0,0,width,height)).save(OUT/(key+'.png'),optimize=True)
        (OUT/(key+'.json')).write_text(json.dumps({'frames':page['frames'],'meta':{'image':key+'.png','size':{'w':width,'h':height}}},separators=(',',':')),encoding='utf8')
        sheets[tier].append({'key':key,'width':width,'height':height})
        for frame in page['frames']:locations[tier][frame]=key
    print(tier,'samples/world unit:',len(sheets[tier]),'pages;',round(sum(p['width']*p['height']*4/1048576 for p in sheets[tier]),2),'MiB full library')
  catalog={'assets':assets,'sheets':sheets,'locations':locations}
  (OUT/'manifest.json').write_text(json.dumps(catalog,indent=2),encoding='utf8')
  (ROOT/'client/game/model-catalog.ts').write_text('// Generated by tools/art/pack_models.py.\nexport const modelCatalog = '+json.dumps(catalog,separators=(',',':'))+' as const;\n',encoding='utf8')
  selected=[a for a in assets if a['type'] in ['residential','commercial','industrial','construction','landscape']]
  sheet=Image.new('RGB',(1600,math.ceil(len(selected)/4)*480),'#e7e5dd');pen=ImageDraw.Draw(sheet)
  for i,a in enumerate(selected):
    p=pictures[a['id']].copy();p.thumbnail((375,425),Image.Resampling.LANCZOS)
    x=i%4*400;y=i//4*480
    sheet.paste(p,(x+(400-p.width)//2,y+425-p.height),p)
    pen.text((x+15,y+442),a['id'],fill='#29302c')
  sheet.save(DOC/'benchmark-library.jpg',quality=95)


if __name__=='__main__':build()
