import type { PolicyDefinition, PolicyEffects } from '../types/governance';
export const GOVERNANCE = {
  analysisInterval: 5, historyLimit: 240, districtLimit: 32, challengeLimit: 64, cooldown: 30, policyDelay: 7, policyRamp: 21,
  taxSmoothing: .08, rentSmoothing: .12, rentMinimum: 12000, rentMaximum: 350000, incomeMinimum: 80000,
  affordableShare: .3, housingPressureThreshold: 65, displacementDepartureDelay: 90,
  housing: { baseRent:22000, landRent:650, levelRent:2800, incomeLevel:18000, incomeLand:500, incomeEmployment:65000, scarcityBase:.7, informalRent:.7, integrationRent:.003 },
  maintenance: { low:-15, high:20, maximum:150, failureCondition:35, failureChance:4, failureDays:3 },
  displacement: { shock:5, shockMaximum:20, shockRecovery:.08, rehouseRate:.1, departureRate:.003 },
  effects: { demandTax:12, attractivenessTax:8, pedestrianCapacity:.4, rentAffordability:70, policyAdministration:25000 },
  taxes: { residential: { min: .1, max: .6, base: .25 }, commercial: { min: 1, max: 8, base: 3.5 }, industrial: { min: 1, max: 8, base: 2.5 } },
} as const;
export const emptyEffects = (): PolicyEffects => ({ lighting:0, prevention:0, commercialPatrol:0, hubSafety:0, residential: 0, commercial: 0, industrial: 0, upgrade: 0, rent: 0, business: 0, transit: 0, walking: 0, drainage: 0, environment: 0, integration: 0, waste: 0 });
// Policy cost is naira per unit of its basis per month at full strength (M8.2). The old flat per-resident
// fees (300–5,200) exceeded the city's entire revenue per resident (about 2,100), so most policies cost more
// than the municipal economy. Costs now track what each programme serves: streets, jobs, drains, depots,
// stops or (informal) residents, at roughly 1–5% of a typical city's revenue; affordable housing is
// deliberately the most expensive (about 9%).
export const POLICIES: PolicyDefinition[] = [
  {id:'street-lighting',name:'Street Lighting Program',category:'Public safety',scope:'both',cost:5000, basis:'roads',requirements:'Connected roads and public electricity.',description:'Improve powered street visibility gradually. Adds electricity and maintenance costs.',effects:{lighting:32}},
  {id:'community-safety',name:'Community Safety Program',category:'Public safety',scope:'both',cost:70, basis:'residents',requirements:'Employment, stable housing and services remain important.',description:'Support prevention and active public space; does not dispatch police or eliminate incidents.',effects:{prevention:9}},
  {id:'commercial-patrol',name:'Commercial Area Patrol',category:'Public safety',scope:'both',cost:30000, basis:'commercial-buildings',requirements:'Staffed road-connected police facilities.',description:'Prioritize commercial patrol from existing capacity; less patrol remains elsewhere.',effects:{commercialPatrol:.25}},
  {id:'hub-safety',name:'Transport Hub Safety',category:'Public safety',scope:'both',cost:50000, basis:'stops',requirements:'Existing transport stops, electricity and police capacity.',description:'Improve hub lighting and prioritize existing patrol; no new officers appear automatically.',effects:{hubSafety:.2}},
  { id:'density', name:'Density encouragement', category:'Housing', scope:'both', cost:50, basis:'residents', requirements:'Existing demand, utilities and services still limit upgrades.', description:'Encourage gradual redevelopment. More residents also need more infrastructure and road capacity.', effects:{residential:4,upgrade:.7} },
  { id:'affordable', name:'Affordable housing programme', category:'Housing', scope:'both', cost:200, basis:'residents', requirements:'Occupied homes; costs scale with residents.', description:'Housing support lowers household costs and encourages homes; municipal spending rises.', effects:{rent:-.2,residential:6} },
  { id:'infill', name:'Infill development', category:'Development', scope:'both', cost:40, basis:'residents', requirements:'Road-connected land beside existing development.', description:'Prioritize existing neighborhoods without bypassing construction or infrastructure requirements.', effects:{residential:5,commercial:3,upgrade:.3} },
  { id:'commerce', name:'Commercial promotion', category:'Economy', scope:'both', cost:220, basis:'commercial-jobs', requirements:'Customers, workers and road access.', description:'Encourage investment, with additional service and transport demand as businesses grow.', effects:{commercial:8,business:.025} },
  { id:'industry', name:'Industrial investment', category:'Economy', scope:'both', cost:180, basis:'industrial-jobs', requirements:'Utilities and workforce remain necessary.', description:'Support workshops and factories. Existing industrial pollution still affects neighbors.', effects:{industrial:8,business:.025} },
  { id:'business', name:'Small business support', category:'Economy', scope:'both', cost:200, basis:'business-jobs', requirements:'Existing businesses and informal livelihoods.', description:'Reduce operating pressure on small firms and support economic integration at a public cost.', effects:{business:.08,integration:.2} },
  { id:'transit', name:'Transit priority', category:'Transport', scope:'both', cost:60, basis:'residents', requirements:'Existing shared routes; this does not create a bus service.', description:'Subsidize shared travel and improve route capacity efficiency; private operators remain.', effects:{transit:.2} },
  { id:'pedestrian', name:'Pedestrian-friendly streets', category:'Transport', scope:'both', cost:3500, basis:'roads', requirements:'Short connected journeys.', description:'Favor walking and local shop activity, reducing local vehicle capacity slightly.', effects:{walking:.35,commercial:3,environment:3} },
  { id:'drainage', name:'Drainage priority', category:'Infrastructure', scope:'both', cost:40000, basis:'drains', requirements:'Existing drainage assets; coverage still depends on location.', description:'Fund slower deterioration and improved capacity of existing drains.', effects:{drainage:20} },
  { id:'waste', name:'Waste collection improvement', category:'Public services', scope:'both', cost:700000, basis:'waste-depots', requirements:'Operating depots, workforce and connected disposal capacity.', description:'Support collection efficiency without inventing trucks or disposal space.', effects:{waste:.15} },
  { id:'green', name:'Environmental stewardship', category:'Environment', scope:'both', cost:35, basis:'residents', requirements:'Existing green space and industrial impacts remain relevant.', description:'Improve local environmental quality through maintenance and cleaner practices.', effects:{environment:5} },
  { id:'integration', name:'Community upgrading & integration', category:'Housing', scope:'both', cost:1200, basis:'informal-residents', requirements:'Roads and reliable public power, water and drainage.', description:'Gradually formalize informal properties when real services are adequate. Formal taxation and housing costs may rise.', effects:{integration:1,commercial:2} },
  { id:'community-upgrade', name:'Informal community upgrading', category:'Housing', scope:'both', cost:800, basis:'informal-residents', requirements:'Connected existing drainage and waste facilities; expand utilities separately.', description:'Improve existing drain maintenance, waste capacity and environmental quality without removing homes or livelihoods.', effects:{drainage:10,waste:.1,environment:3} },
  { id:'formalization', name:'Supported property formalization', category:'Development', scope:'both', cost:900, basis:'informal-residents', requirements:'Existing properties need reliable power, water, drainage and road access.', description:'Accelerate gradual tenure formalization once real services are adequate. Full property taxation and higher housing costs follow formal tenure.', effects:{integration:1.5} },
];
export const OBJECTIVES = { affordable:'Affordable city', commercial:'Commercial hub', industrial:'Industrial powerhouse', transit:'Transit-oriented city', resilient:'Resilient city', quality:'High quality of life' } as const;
