import type { City } from '../types/city';
import { TRANSIT, TRANSIT_FACILITIES } from './transit-config';
const record = (v: any) => v !== null && typeof v === 'object' && !Array.isArray(v);
const finite = (v: any, min = 0, max = Number.MAX_SAFE_INTEGER) => typeof v === 'number' && Number.isFinite(v) && v >= min && v <= max;
const tile = (v: any) => Number.isInteger(v) && v >= 0 && v < 1024;
const numbers = (v: any, keys: string[], max = Number.MAX_SAFE_INTEGER) => record(v) && keys.every(k => finite(v[k], 0, max));
const path = (p: any) => Array.isArray(p) && p.length <= 8192 && p.every(tile) && p.every((id: number, i: number) => i === 0 || Math.abs(id % 32 - p[i - 1] % 32) + Math.abs(Math.floor(id / 32) - Math.floor(p[i - 1] / 32)) === 1);
const accessKeys = ['access', 'demand', 'ridership', 'jobs45', 'education', 'healthcare', 'commerce', 'center', 'firstMile', 'lastMile', 'tod', 'throughput'];
export function validTransit(city: City): boolean {
  const t = city.transit as any;
  if (!record(t) || !numbers(t, ['revision', 'nextId']) || !Number.isInteger(t.nextId) || !finite(t.lastTick, -1) || !finite(t.subsidyRate, 0, 80) || !['neutral', 'integrate', 'support'].includes(t.integration)) return false;
  if (!Array.isArray(t.stops) || t.stops.length > TRANSIT.stopLimit || new Set(t.stops.map((s: any) => s.id)).size !== t.stops.length || new Set(t.stops.map((s: any) => s.tileId)).size !== t.stops.length || !t.stops.every((s: any) => record(s) && typeof s.id === 'string' && typeof s.name === 'string' && s.name.length <= 100 && s.kind in TRANSIT_FACILITIES && tile(s.tileId) && tile(s.anchor) && numbers(s, ['builtAt', 'capacity', 'boardings', 'transfers', 'demand', 'crowding']) && ['condition', 'accessibility', 'nightSafety', 'lighting'].every(k => finite(s[k], 0, 100)) && Array.isArray(s.routes))) return false;
  const stops = new Map<string, any>(t.stops.map((s: any) => [s.id, s]));
  if (!Array.isArray(t.routes) || t.routes.length > TRANSIT.routeLimit || new Set(t.routes.map((r: any) => r.id)).size !== t.routes.length || !t.routes.every((r: any) => record(r) && typeof r.id === 'string' && typeof r.name === 'string' && r.name.length <= 80 && ['bus', 'brt'].includes(r.mode) && finite(r.color, 0, 0xffffff) && typeof r.legacy === 'boolean' && typeof r.suspended === 'boolean' && ['active', 'suspended', 'disrupted', 'no-depot'].includes(r.status) && Array.isArray(r.stops) && r.stops.length <= TRANSIT.stopRouteLimit && r.stops.every((s: any) => stops.has(s)) && new Set(r.stops).size === r.stops.length && (r.stops.length >= 2 || r.status === 'disrupted' || r.suspended) && path(r.path) && Number.isInteger(r.vehicles) && finite(r.vehicles, 1, TRANSIT.fleetLimit) && finite(r.availableVehicles, 0, r.vehicles) && Number.isInteger(r.availableVehicles) && numbers(r, ['length', 'headway', 'capacity', 'ridership', 'demand', 'speed', 'wait', 'minutes', 'operatingCost', 'revenue', 'subsidy', 'crowding', 'createdAt', 'deadhead']) && finite(r.fare, 0, TRANSIT.fareMaximum) && finite(r.reliability, 0, 100) && Array.isArray(r.segmentLoads) && r.segmentLoads.length === Math.max(0, r.stops.length - 1) && r.segmentLoads.every((n: any) => finite(n)) && (!r.legacy || city.mobility.routes.some(old => old.id === r.id && old.mode === 'bus')))) return false;
  const routes = new Set(t.routes.map((r: any) => r.id)), allRoutes = new Set([...routes, ...city.mobility.routes.map(r => r.id)]);
  if (!t.stops.every((s: any) => s.routes.every((id: any) => routes.has(id)))) return false;
  if (!Array.isArray(t.corridors) || t.corridors.length > 1024 || new Set(t.corridors).size !== t.corridors.length || !t.corridors.every((id: any) => tile(id) && city.tiles[id].road && ['avenue', 'major'].includes(city.tiles[id].roadClass ?? ''))) return false;
  if (!record(t.junctions) || Object.keys(t.junctions).length > 1024 || !Object.entries(t.junctions).every(([id, kind]) => tile(Number(id)) && city.tiles[Number(id)].road && ['signal', 'high-capacity', 'roundabout'].includes(String(kind)))) return false;
  if (!record(t.works) || Object.keys(t.works).length > 1024 || !Object.entries(t.works).every(([id, until]) => tile(Number(id)) && finite(until))) return false;
  if (!Array.isArray(t.local) || t.local.length !== 1024 || !t.local.every((l: any) => numbers(l, accessKeys) && ['access', 'firstMile', 'lastMile'].every(k => finite(l[k], 0, 100)) && finite(l.tod, 0, TRANSIT.todMaximum))) return false;
  if (!record(t.districts) || Object.keys(t.districts).length > 32 || !Object.entries(t.districts).every(([id, metrics]) => city.governance.districts.some(d => d.id === id) && numbers(metrics, accessKeys))) return false;
  if (!numbers(t.finance, ['bus', 'brt', 'stations', 'terminals', 'depots', 'fares', 'subsidy', 'recovery']) || !numbers(t.stats, ['ridership', 'access', 'jobs45', 'wait', 'reliability', 'throughput', 'crowding', 'depotCapacity', 'assignedFleet']) || typeof t.stats.profile !== 'string') return false;
  if (!Array.isArray(t.history) || t.history.length > TRANSIT.historyLimit || !t.history.every((h: any) => numbers(h, ['tick', 'ridership', 'access', 'jobs45', 'wait', 'subsidy']))) return false;
  if (!Array.isArray(t.transfers) || t.transfers.length > 2304 || !t.transfers.every((f: any) => record(f) && allRoutes.has(f.from) && allRoutes.has(f.to) && tile(f.tileId) && finite(f.passengers))) return false;
  if (!Array.isArray(t.demand) || t.demand.length > 768 || !t.demand.every((d: any) => record(d) && city.mobility.flows.some(f => f.id === d.flowId) && numbers(d, ['passengers', 'minutes', 'cost', 'transfers']) && d.transfers <= TRANSIT.transfers && Array.isArray(d.legs) && d.legs.length <= TRANSIT.transfers + 1 && d.legs.every((l: any) => allRoutes.has(l.routeId) && ['bus', 'brt', 'keke', 'danfo'].includes(l.mode) && typeof l.from === 'string' && typeof l.to === 'string'))) return false;
  return true;
}
